unit UDM;

interface

uses
     Windows, Forms, SysUtils, Classes, DB, ImgList, Controls, DBClient, Dialogs,
     SqlExpr, Provider, RLPreviewForm, RLFilters, RLPDFFilter, FMTBcd,
     RLXLSFilter, RLHTMLFilter, ExtDlgs, shellapi, RLDraftFilter, ADODB, variants,
     RLRichFilter, dateutils, midaslib,Menus, Grids, DBGrids, WideStrings,
     DBXInterbase, Data.DBXFirebird;

type
     TDM = class(TDataModule)
          SQLConnection: TSQLConnection;
          QItemUsuario: TSQLQuery;
          QItemUsuarioITEUSUARIO: TStringField;
          QItemUsuarioITEPROGRAMA: TIntegerField;
          QItemUsuarioITEACESSO: TStringField;
          QItemUsuarioITEINSERCAO: TStringField;
          QItemUsuarioITEALTERACAO: TStringField;
          QItemUsuarioITEEXCLUSAO: TStringField;
          QItemUsuarioITERELATORIO: TStringField;
          CDSUsuario: TClientDataSet;
          CDSUsuarioUSULOGIN: TStringField;
          CDSUsuarioUSUNOME: TStringField;
          CDSUsuarioUSUSENHA: TStringField;
          DSPUsuario: TDataSetProvider;
          QUsuario: TSQLQuery;
          QUsuarioUSULOGIN: TStringField;
          QUsuarioUSUNOME: TStringField;
          QUsuarioUSUSENHA: TStringField;
          CDSItemUsuario: TClientDataSet;
          CDSItemUsuarioITEUSUARIO: TStringField;
          CDSItemUsuarioITEPROGRAMA: TIntegerField;
          CDSItemUsuarioITEACESSO: TStringField;
          CDSItemUsuarioITEINSERCAO: TStringField;
          CDSItemUsuarioITEALTERACAO: TStringField;
          CDSItemUsuarioITEEXCLUSAO: TStringField;
          CDSItemUsuarioITERELATORIO: TStringField;
          DSItemUsuario: TDataSource;
          DSUsuario: TDataSource;
          ImageList: TImageList;
          CDSNovo: TClientDataSet;
          SaveDialog: TSaveDialog;
          OpenDialog: TOpenDialog;
          SaveDialogHTML: TSaveDialog;
          SaveXls: TSaveDialog;
          QMax: TSQLQuery;
          QMaxCOD: TIntegerField;
          QChave: TSQLQuery;
          QChaveCAMPO: TStringField;
          OpenPictureDialog: TOpenPictureDialog;
          QParamEmp: TSQLQuery;
          CDSParamEmp: TClientDataSet;
          DSPParamEmp: TDataSetProvider;
          DSParamEmp: TDataSource;
          QPrograma: TSQLQuery;
          QProgramaPROCOD: TIntegerField;
          QProgramaPRONOME: TStringField;
          CDSPrograma: TClientDataSet;
          CDSProgramaPROCOD: TIntegerField;
          CDSProgramaPRONOME: TStringField;
          DSPPrograma: TDataSetProvider;
          DSPrograma: TDataSource;
          QCidade: TSQLQuery;
          QCidadeCIDCOD: TIntegerField;
          QCidadeCIDNOME: TStringField;
          QCidadeCIDUF: TStringField;
          CDSCidade: TClientDataSet;
          CDSCidadeCIDCOD: TIntegerField;
          CDSCidadeCIDNOME: TStringField;
          CDSCidadeCIDUF: TStringField;
          DSPCidade: TDataSetProvider;
          DSCidade: TDataSource;
          QParamEmpEMPCOD: TIntegerField;
          QParamEmpEMPNOME: TStringField;
          QParamEmpEMPRAZAO: TStringField;
          QParamEmpEMPENDERECO: TStringField;
          QParamEmpEMPBAIRRO: TStringField;
          QParamEmpEMPNUMERO: TIntegerField;
          QParamEmpEMPCIDADE: TIntegerField;
          QParamEmpEMPRESPONSAVEL: TStringField;
          QParamEmpEMPCAB: TBlobField;
          QParamEmpEMPFIGURA: TBlobField;
          QParamEmpEMPFONE: TStringField;
          QParamEmpEMPFAX: TStringField;
          QParamEmpEMPSITE: TStringField;
          QParamEmpEMPEMAIL: TStringField;
          QParamEmpEMPCPFCNPJ: TStringField;
          QParamEmpEMPIE: TStringField;
          CDSParamEmpEMPCOD: TIntegerField;
          CDSParamEmpEMPNOME: TStringField;
          CDSParamEmpEMPRAZAO: TStringField;
          CDSParamEmpEMPENDERECO: TStringField;
          CDSParamEmpEMPBAIRRO: TStringField;
          CDSParamEmpEMPNUMERO: TIntegerField;
          CDSParamEmpEMPCIDADE: TIntegerField;
          CDSParamEmpEMPRESPONSAVEL: TStringField;
          CDSParamEmpEMPCAB: TBlobField;
          CDSParamEmpEMPFIGURA: TBlobField;
          CDSParamEmpEMPFONE: TStringField;
          CDSParamEmpEMPFAX: TStringField;
          CDSParamEmpEMPSITE: TStringField;
          CDSParamEmpEMPEMAIL: TStringField;
          CDSParamEmpEMPCPFCNPJ: TStringField;
          CDSParamEmpEMPIE: TStringField;
          QInstituto: TSQLQuery;
          CDSInstituto: TClientDataSet;
          DSPInstituto: TDataSetProvider;
          DSInstituto: TDataSource;
          QInstitutoINSNOME: TStringField;
          QInstitutoINSENDERECO: TStringField;
          QInstitutoINSBAIRRO: TStringField;
          QInstitutoINSCIDADE: TStringField;
          QInstitutoINSFONE: TStringField;
          QInstitutoINSFAX: TStringField;
          QInstitutoINSSITE: TStringField;
          QInstitutoINSEMAIL: TStringField;
          QInstitutoINSLOGO: TBlobField;
          QInstitutoINSVERSAO: TIntegerField;
          CDSInstitutoINSNOME: TStringField;
          CDSInstitutoINSENDERECO: TStringField;
          CDSInstitutoINSBAIRRO: TStringField;
          CDSInstitutoINSCIDADE: TStringField;
          CDSInstitutoINSFONE: TStringField;
          CDSInstitutoINSFAX: TStringField;
          CDSInstitutoINSSITE: TStringField;
          CDSInstitutoINSEMAIL: TStringField;
          CDSInstitutoINSLOGO: TBlobField;
          CDSInstitutoINSVERSAO: TIntegerField;
          QBanco: TSQLQuery;
          CDSBanco: TClientDataSet;
          DSPBanco: TDataSetProvider;
          DSBanco: TDataSource;
          QBancoBANCOD: TIntegerField;
          QBancoBANNOME: TStringField;
          QBancoBANAGENCIA: TStringField;
          QBancoBANCONTA: TStringField;
          QBancoBANCONTATO: TStringField;
          QBancoBANFONE: TStringField;
          QBancoBANFAX: TStringField;
          QBancoBANEMAIL: TStringField;
          CDSBancoBANCOD: TIntegerField;
          CDSBancoBANNOME: TStringField;
          CDSBancoBANAGENCIA: TStringField;
          CDSBancoBANCONTA: TStringField;
          CDSBancoBANCONTATO: TStringField;
          CDSBancoBANFONE: TStringField;
          CDSBancoBANFAX: TStringField;
          CDSBancoBANEMAIL: TStringField;
          QDisciplina: TSQLQuery;
          CDSDisciplina: TClientDataSet;
          DSPDisciplina: TDataSetProvider;
          DSDisciplina: TDataSource;
          QDisciplinaDISCOD: TIntegerField;
          QDisciplinaDISNOME: TStringField;
          CDSDisciplinaDISCOD: TIntegerField;
          CDSDisciplinaDISNOME: TStringField;
          QGrupoPro: TSQLQuery;
          CDSGrupoPro: TClientDataSet;
          DSPGrupoPro: TDataSetProvider;
          DSGrupoPro: TDataSource;
          QGrupoProGRUPROCOD: TIntegerField;
          QGrupoProGRUPRONOME: TStringField;
          CDSGrupoProGRUPROCOD: TIntegerField;
          CDSGrupoProGRUPRONOME: TStringField;
          QHistPadrao: TSQLQuery;
          CDSHistPadrao: TClientDataSet;
          DSPHistPadrao: TDataSetProvider;
          DSHistPadrao: TDataSource;
          QHistPadraoHISCOD: TIntegerField;
          QHistPadraoHISNOME: TStringField;
          CDSHistPadraoHISCOD: TIntegerField;
          CDSHistPadraoHISNOME: TStringField;
          QMensalidade: TSQLQuery;
          CDSMensalidade: TClientDataSet;
          DSPMensalidade: TDataSetProvider;
          DSMensalidade: TDataSource;
          QMensalidadeMENALUNO: TIntegerField;
          QMensalidadeMENNUMERO: TIntegerField;
          QMensalidadeMENVENCIMENTO: TDateField;
          QMensalidadeMENBANCO: TIntegerField;
          QMensalidadeMENVALOR: TFloatField;
          QMensalidadeMENACRESCIMO: TFloatField;
          QMensalidadeMENDESCONTO: TFloatField;
          QMensalidadeMENVALORPAGO: TFloatField;
          QMensalidadeMENDATAPAGAMENTO: TDateField;
          CDSMensalidadeMENALUNO: TIntegerField;
          CDSMensalidadeMENNUMERO: TIntegerField;
          CDSMensalidadeMENVENCIMENTO: TDateField;
          CDSMensalidadeMENBANCO: TIntegerField;
          CDSMensalidadeMENVALOR: TFloatField;
          CDSMensalidadeMENACRESCIMO: TFloatField;
          CDSMensalidadeMENDESCONTO: TFloatField;
          CDSMensalidadeMENVALORPAGO: TFloatField;
          CDSMensalidadeMENDATAPAGAMENTO: TDateField;
          CDSAluno: TClientDataSet;
          DSPAluno: TDataSetProvider;
          QAluno: TSQLQuery;
          DSAluno: TDataSource;
          QAlunoALUCOD: TIntegerField;
          QAlunoALUNOME: TStringField;
          QAlunoALUENDERECO: TStringField;
          QAlunoALUBAIRRO: TStringField;
          QAlunoALUCIDADE: TIntegerField;
          QAlunoALUCEP: TStringField;
          QAlunoALUFONE: TStringField;
          QAlunoALUFAX: TStringField;
          QAlunoALUCELULAR: TStringField;
          QAlunoALUEMAIL: TStringField;
          QAlunoALUCPF: TStringField;
          QAlunoALUIDENTIDADE: TStringField;
          QAlunoALUCARTEIRA: TStringField;
          QAlunoALUOCORRENCIAS: TMemoField;
          QAlunoALUHISTESCOLAR: TMemoField;
          CDSAlunoALUCOD: TIntegerField;
          CDSAlunoALUNOME: TStringField;
          CDSAlunoALUENDERECO: TStringField;
          CDSAlunoALUBAIRRO: TStringField;
          CDSAlunoALUCIDADE: TIntegerField;
          CDSAlunoALUCEP: TStringField;
          CDSAlunoALUFONE: TStringField;
          CDSAlunoALUFAX: TStringField;
          CDSAlunoALUCELULAR: TStringField;
          CDSAlunoALUEMAIL: TStringField;
          CDSAlunoALUCPF: TStringField;
          CDSAlunoALUIDENTIDADE: TStringField;
          CDSAlunoALUCARTEIRA: TStringField;
          CDSAlunoALUOCORRENCIAS: TMemoField;
          CDSAlunoALUHISTESCOLAR: TMemoField;
          QProfessorDisciplina: TSQLQuery;
          CDSProfessor: TClientDataSet;
          DSPProfessor: TDataSetProvider;
          QProfessor: TSQLQuery;
          CDSProfessorDisciplina: TClientDataSet;
          DSProfessorDisciplina: TDataSource;
          DSProfessor: TDataSource;
          QProfessorPROCOD: TIntegerField;
          QProfessorPRONOME: TStringField;
          QProfessorPROENDERECO: TStringField;
          QProfessorPROBAIRRO: TStringField;
          QProfessorPROCIDADE: TIntegerField;
          QProfessorPROCEP: TStringField;
          QProfessorPROFONE: TStringField;
          QProfessorPROFAX: TStringField;
          QProfessorPROCELULAR: TStringField;
          QProfessorPROEMAIL: TStringField;
          QProfessorPROSITE: TStringField;
          QProfessorPROCPF: TStringField;
          QProfessorPRONOTAFISCAL: TStringField;
          QProfessorPROGRUPO: TIntegerField;
          QProfessorPROOBS: TStringField;
          QProfessorPROCURRICULUM: TMemoField;
          QProfessorPROTITULACAO: TMemoField;
          CDSProfessorPROCOD: TIntegerField;
          CDSProfessorPRONOME: TStringField;
          CDSProfessorPROENDERECO: TStringField;
          CDSProfessorPROBAIRRO: TStringField;
          CDSProfessorPROCIDADE: TIntegerField;
          CDSProfessorPROCEP: TStringField;
          CDSProfessorPROFONE: TStringField;
          CDSProfessorPROFAX: TStringField;
          CDSProfessorPROCELULAR: TStringField;
          CDSProfessorPROEMAIL: TStringField;
          CDSProfessorPROSITE: TStringField;
          CDSProfessorPROCPF: TStringField;
          CDSProfessorPRONOTAFISCAL: TStringField;
          CDSProfessorPROGRUPO: TIntegerField;
          CDSProfessorPROOBS: TStringField;
          CDSProfessorPROCURRICULUM: TMemoField;
          CDSProfessorPROTITULACAO: TMemoField;
          QProfessorDisciplinaPRODISPROFESSOR: TIntegerField;
          QProfessorDisciplinaPRODISDISCIPLINA: TIntegerField;
          QProfessorDisciplinaPRODISOBS: TStringField;
          CDSProfessorDisciplinaPRODISPROFESSOR: TIntegerField;
          CDSProfessorDisciplinaPRODISDISCIPLINA: TIntegerField;
          CDSProfessorDisciplinaPRODISOBS: TStringField;
          QCursoDisciplina: TSQLQuery;
          CDSCurso: TClientDataSet;
          DSPCurso: TDataSetProvider;
          QCurso: TSQLQuery;
          CDSCursoDisciplina: TClientDataSet;
          DSCursoDisciplina: TDataSource;
          DSCurso: TDataSource;
          QCursoCURCOD: TIntegerField;
          QCursoCURNOME: TStringField;
          QCursoCURTURMA: TStringField;
          QCursoCURCARGA: TIntegerField;
          QCursoCURVALOR: TFloatField;
          QCursoCURPERCDESCONTO: TFloatField;
          QCursoCURDESCONTO: TFloatField;
          QCursoCURVENCIMENTO: TSmallintField;
          QCursoCURTCC: TStringField;
          QCursoCURINICIO: TDateField;
          QCursoCURFIM: TDateField;
          CDSCursoCURCOD: TIntegerField;
          CDSCursoCURNOME: TStringField;
          CDSCursoCURTURMA: TStringField;
          CDSCursoCURCARGA: TIntegerField;
          CDSCursoCURVALOR: TFloatField;
          CDSCursoCURPERCDESCONTO: TFloatField;
          CDSCursoCURDESCONTO: TFloatField;
          CDSCursoCURVENCIMENTO: TSmallintField;
          CDSCursoCURTCC: TStringField;
          CDSCursoCURINICIO: TDateField;
          CDSCursoCURFIM: TDateField;
          QCursoDisciplinaCURDISCURSO: TIntegerField;
          QCursoDisciplinaCURDISDISCIPLINA: TIntegerField;
          QCursoDisciplinaCURDISPROFESSOR: TIntegerField;
          CDSCursoDisciplinaCURDISCURSO: TIntegerField;
          CDSCursoDisciplinaCURDISDISCIPLINA: TIntegerField;
          CDSCursoDisciplinaCURDISPROFESSOR: TIntegerField;
          QPlanoNegocios: TSQLQuery;
          CDSPlanoNegocios: TClientDataSet;
          DSPPlanoNegocios: TDataSetProvider;
          DSPlanoNegocios: TDataSource;
          QPlanoNegociosPLANEGCOD: TIntegerField;
          QPlanoNegociosPLANEGNOME: TStringField;
          CDSPlanoNegociosPLANEGCOD: TIntegerField;
          CDSPlanoNegociosPLANEGNOME: TStringField;
          QPlanoConta: TSQLQuery;
          CDSPlanoConta: TClientDataSet;
          DSPPlanoConta: TDataSetProvider;
          DSPlanoConta: TDataSource;
          QPlanoContaPLACODRED: TStringField;
          QPlanoContaPLACODANA: TStringField;
          QPlanoContaPLADESCRICAO: TStringField;
          CDSPlanoContaPLACODRED: TStringField;
          CDSPlanoContaPLACODANA: TStringField;
          CDSPlanoContaPLADESCRICAO: TStringField;
          QLctoContabil: TSQLQuery;
          DSPLctoContabil: TDataSetProvider;
          DSLctoContabil: TDataSource;
          CDSLctoContabil: TClientDataSet;
          CDSLctoContabilLCTNUMERO: TIntegerField;
          CDSLctoContabilLCTDATA: TDateField;
          CDSLctoContabilLCTDEBITO: TStringField;
          CDSLctoContabilLCTCREDITO: TStringField;
          CDSLctoContabilLCTHISTPADRAO: TIntegerField;
          CDSLctoContabilLCTPLANONEGOCIOS: TIntegerField;
          CDSLctoContabilLCTVALOR: TFloatField;
          CDSLctoContabildebito: TStringField;
          CDSLctoContabilcredito: TStringField;
          CDSLctoContabilhistpadrao: TStringField;
          CDSLctoContabilplanonegocios: TStringField;
          QBancoBANCELULAR: TStringField;
          CDSBancoBANCELULAR: TStringField;
          QCursoCURLIQUIDO: TFloatField;
          CDSCursoCURLIQUIDO: TFloatField;
          CDSCursoliquido: TFloatField;
          QCursoDisciplinaCURDISHORASAULA: TIntegerField;
          CDSCursoDisciplinaCURDISHORASAULA: TIntegerField;
          QParamEmpEMPFIGURAALT: TBlobField;
          CDSParamEmpEMPFIGURAALT: TBlobField;
          QExec: TSQLQuery;
          DSPExec: TDataSetProvider;
          CDSExec: TClientDataSet;
          QProfessorGrupo: TSQLQuery;
          CDSProfessorGrupo: TClientDataSet;
          DSProfessorGrupo: TDataSource;
          QProfessorGrupoPROGRUPROFESSOR: TIntegerField;
          QProfessorGrupoPROGRUGRUPO: TIntegerField;
          QProfessorGrupoPROGRUOBS: TStringField;
          CDSProfessorGrupoPROGRUPROFESSOR: TIntegerField;
          CDSProfessorGrupoPROGRUGRUPO: TIntegerField;
          CDSProfessorGrupoPROGRUOBS: TStringField;
          QProfessorPRORESUMOTITULACAO: TStringField;
          CDSProfessorPRORESUMOTITULACAO: TStringField;
          QCursoCURCOORDENADOR: TIntegerField;
          QCursoCURSISTEMAAVALIACAO: TStringField;
          QCursoCURCRITERIOSAVALIACAO: TStringField;
          QCursoCURSECRETARIO: TStringField;
          CDSCursoCURCOORDENADOR: TIntegerField;
          CDSCursoCURSISTEMAAVALIACAO: TStringField;
          CDSCursoCURCRITERIOSAVALIACAO: TStringField;
          CDSCursoCURSECRETARIO: TStringField;
          QAlunoALUNACIONALIDADE: TStringField;
          QAlunoALUNASCIMENTO: TDateField;
          QAlunoALUNATURALIDADE: TIntegerField;
          CDSAlunoALUNACIONALIDADE: TStringField;
          CDSAlunoALUNASCIMENTO: TDateField;
          CDSAlunoALUNATURALIDADE: TIntegerField;
          QAlunoDisciplina: TSQLQuery;
          CDSAlunoDisciplina: TClientDataSet;
          DSAlunoDisciplina: TDataSource;
          QProfessorPROCURRICULUMLATTES: TStringField;
          CDSProfessorPROCURRICULUMLATTES: TStringField;
          QAlunoALUSITUACAO: TStringField;
          QAlunoALUESTADOCIVIL: TStringField;
          QAlunoALUORGAOEXPEDIDOR: TStringField;
          QAlunoALUDATAEXPEDICAO: TDateField;
          QAlunoALUSEXO: TStringField;
          QAlunoALUNOMEMAE: TStringField;
          QAlunoALUNOMEPAI: TStringField;
          QAlunoALUMIDIA: TStringField;
          CDSAlunoALUSITUACAO: TStringField;
          CDSAlunoALUESTADOCIVIL: TStringField;
          CDSAlunoALUORGAOEXPEDIDOR: TStringField;
          CDSAlunoALUDATAEXPEDICAO: TDateField;
          CDSAlunoALUSEXO: TStringField;
          CDSAlunoALUNOMEPAI: TStringField;
          CDSAlunoALUNOMEMAE: TStringField;
          CDSAlunoALUMIDIA: TStringField;
          QMensalidadeMENOBS: TStringField;
          CDSMensalidadeMENOBS: TStringField;
          CDSMensalidadeliquido: TFloatField;
          CDSLctoContabilCONTACREDITO: TStringField;
          CDSLctoContabilCONTADEBITO: TStringField;
          QMensalidadeALUNOME: TStringField;
          CDSMensalidadeALUNOME: TStringField;
          QAlunoALUINDICACAO: TStringField;
          QAlunoALUINDICACAOVALOR: TFloatField;
          QAlunoALUINDICACAOPAGO: TStringField;
          CDSAlunoALUINDICACAO: TStringField;
          CDSAlunoALUINDICACAOVALOR: TFloatField;
          CDSAlunoALUINDICACAOPAGO: TStringField;
          QInstitutoINSCNPJ: TStringField;
          CDSInstitutoINSCNPJ: TStringField;
          QPlanoContaPLANIVEL: TIntegerField;
          CDSPlanoContaPLANIVEL: TIntegerField;
          QCursoCURPLANONEGOCIOS: TIntegerField;
          CDSCursoCURPLANONEGOCIOS: TIntegerField;
          QAlunoALUCURSO: TIntegerField;
          QAlunoALUORIENTADOR: TIntegerField;
          QAlunoALUCARTEIRINHA: TStringField;
          QAlunoALUCRACHA: TStringField;
          QAlunoALUCERTIFICADO: TStringField;
          QAlunoCURNOME: TStringField;
          QAlunoCURTURMA: TStringField;
          CDSAlunoALUCURSO: TIntegerField;
          CDSAlunoALUORIENTADOR: TIntegerField;
          CDSAlunoALUCARTEIRINHA: TStringField;
          CDSAlunoALUCRACHA: TStringField;
          CDSAlunoALUCERTIFICADO: TStringField;
          QAlunoMensalidade: TSQLQuery;
          CDSAlunoMensalidade: TClientDataSet;
          DSAlunoMensalidade: TDataSource;
          QAlunoMensalidadeMENALUNO: TIntegerField;
          QAlunoMensalidadeMENNUMERO: TIntegerField;
          QAlunoMensalidadeMENVENCIMENTO: TDateField;
          QAlunoMensalidadeMENVALOR: TFloatField;
          QAlunoMensalidadeMENDESCONTO: TFloatField;
          QAlunoMensalidadeMENVALORPAGO: TFloatField;
          QAlunoMensalidadeMENDATAPAGAMENTO: TDateField;
          QAlunoMensalidadeMENLIQUIDO: TFloatField;
          CDSAlunoMensalidadeMENALUNO: TIntegerField;
          CDSAlunoMensalidadeMENNUMERO: TIntegerField;
          CDSAlunoMensalidadeMENVENCIMENTO: TDateField;
          CDSAlunoMensalidadeMENVALOR: TFloatField;
          CDSAlunoMensalidadeMENDESCONTO: TFloatField;
          CDSAlunoMensalidadeMENVALORPAGO: TFloatField;
          CDSAlunoMensalidadeMENDATAPAGAMENTO: TDateField;
          CDSAlunoMensalidadeMENLIQUIDO: TFloatField;
          QParametro: TSQLQuery;
          CDSParametro: TClientDataSet;
          DSPParametro: TDataSetProvider;
          DSParametro: TDataSource;
          QParametroPARCOD: TIntegerField;
          QParametroPARNOME: TStringField;
          QParametroPARVALOR: TStringField;
          CDSParametroPARCOD: TIntegerField;
          CDSParametroPARNOME: TStringField;
          CDSParametroPARVALOR: TStringField;
          QAlunoALUCURSOINICIO: TDateField;
          QAlunoALUCURSOFIM: TDateField;
          CDSAlunoALUCURSOINICIO: TDateField;
          CDSAlunoALUCURSOFIM: TDateField;
          QAlunoDisciplinaALUDISALUNO: TIntegerField;
          QAlunoDisciplinaALUDISDISCIPLINA: TIntegerField;
          QAlunoDisciplinaALUDISPROFESSOR: TIntegerField;
          QAlunoDisciplinaALUDISFREQUENCIA: TFloatField;
          QAlunoDisciplinaPRONOME: TStringField;
          CDSAlunoDisciplinaALUDISALUNO: TIntegerField;
          CDSAlunoDisciplinaALUDISDISCIPLINA: TIntegerField;
          CDSAlunoDisciplinaALUDISPROFESSOR: TIntegerField;
          CDSAlunoDisciplinaALUDISFREQUENCIA: TFloatField;
          CDSAlunoDisciplinaALUDISNOTA: TFloatField;
          CDSAlunoDisciplinaPRONOME: TStringField;
          QAlunoLanc: TSQLQuery;
          CDSAlunoLanc: TClientDataSet;
          DSPAlunoLanc: TDataSetProvider;
          DSAlunoLanc: TDataSource;
          QAlunoLancALUDISALUNO: TIntegerField;
          QAlunoLancALUDISDISCIPLINA: TIntegerField;
          QAlunoLancALUDISPROFESSOR: TIntegerField;
          QAlunoLancALUDISFREQUENCIA: TFloatField;
          QAlunoLancALUDISNOTA: TFloatField;
          CDSAlunoLancALUDISALUNO: TIntegerField;
          CDSAlunoLancALUDISDISCIPLINA: TIntegerField;
          CDSAlunoLancALUDISPROFESSOR: TIntegerField;
          CDSAlunoLancALUDISFREQUENCIA: TFloatField;
          CDSAlunoLancALUDISNOTA: TFloatField;
          CDSAlunoLancaluno: TStringField;
          CDSChave: TClientDataSet;
          DSPChave: TDataSetProvider;
          CDSChaveCAMPO: TStringField;
          QMensalidadeMENLCTOCONTABILMENSALIDADE: TIntegerField;
          QMensalidadeMENLCTOCONTABILDESCONTOS: TIntegerField;
          QMensalidadeMENLCTOCONTABILJUROS: TIntegerField;
          CDSMensalidadeMENLCTOCONTABILMENSALIDADE: TIntegerField;
          CDSMensalidadeMENLCTOCONTABILDESCONTOS: TIntegerField;
          CDSMensalidadeMENLCTOCONTABILJUROS: TIntegerField;
          QAlunoLancALUNOME: TStringField;
          CDSAlunoLancALUNOME: TStringField;
          QExiste: TSQLQuery;
          QBancoBANAGENCIADIGITO: TIntegerField;
          QBancoBANNOMENOBANCO: TStringField;
          QBancoBANCONTANUMERO: TIntegerField;
          QBancoBANCONTADIGITO: TIntegerField;
          QBancoBANCEDENTECODIGO: TIntegerField;
          QBancoBANCEDENTEDIGITO: TIntegerField;
          QBancoBANCARTEIRA: TStringField;
          QBancoBANULTIMORETORNO: TIntegerField;
          QBancoBANOPERACAO: TIntegerField;
          QBancoBANDIAMULTA: TFloatField;
          QBancoBANDIADESCONTO: TFloatField;
          QBancoBANLIMITECREDITO: TFloatField;
          CDSBancoBANAGENCIADIGITO: TIntegerField;
          CDSBancoBANNOMENOBANCO: TStringField;
          CDSBancoBANCONTANUMERO: TIntegerField;
          CDSBancoBANCONTADIGITO: TIntegerField;
          CDSBancoBANCEDENTECODIGO: TIntegerField;
          CDSBancoBANCEDENTEDIGITO: TIntegerField;
          CDSBancoBANCARTEIRA: TStringField;
          CDSBancoBANULTIMORETORNO: TIntegerField;
          CDSBancoBANDIAMULTA: TFloatField;
          CDSBancoBANDIADESCONTO: TFloatField;
          CDSBancoBANMULTACARENCIA: TFloatField;
          CDSBancoBANLIMITECREDITO: TFloatField;
          QBancoBANMULTACARENCIA: TFloatField;
          QBancoBANACEITE: TStringField;
          CDSBancoBANACEITE: TStringField;
          QBancoBANESPECIE: TIntegerField;
          QBancoBANEMISSAO: TIntegerField;
          CDSBancoBANOPERACAO: TIntegerField;
          CDSBancoBANESPECIE: TIntegerField;
          CDSBancoBANEMISSAO: TIntegerField;
          SaveDialogBmp: TSaveDialog;
          QTabela: TSQLQuery;
          CDSTabela: TClientDataSet;
          DSPTabela: TDataSetProvider;
          QTabelaTABELA: TStringField;
          CDSTabelaTABELA: TStringField;
          QTrigger: TSQLQuery;
          CDSTrigger: TClientDataSet;
          DSPTrigger: TDataSetProvider;
          QTriggerNOMETRIGGER: TStringField;
          CDSTriggerNOMETRIGGER: TStringField;
          QFormaPgto: TSQLQuery;
          CDSFormaPgto: TClientDataSet;
          DSPFormaPgto: TDataSetProvider;
          DSFormaPgto: TDataSource;
          QFormaPgtoFORCOD: TIntegerField;
          QFormaPgtoFORNOME: TStringField;
          CDSFormaPgtoFORCOD: TIntegerField;
          CDSFormaPgtoFORNOME: TStringField;
          QMensalidadeMENFORMAPGTO: TIntegerField;
          CDSMensalidadeMENFORMAPGTO: TIntegerField;
          QBancoBANMENSAGEM: TStringField;
          CDSBancoBANMENSAGEM: TStringField;
          QProfessorPROFOTO: TBlobField;
          CDSProfessorPROFOTO: TBlobField;
          QAlunoALUMONODATA: TDateField;
          QAlunoALUMONONOTA: TFloatField;
          CDSAlunoALUMONODATA: TDateField;
          CDSAlunoALUMONONOTA: TFloatField;
          QAlunoALUBLOQ: TStringField;
          QAlunoALUBLOQDATA: TDateField;
          CDSAlunoALUBLOQ: TStringField;
          CDSAlunoALUBLOQDATA: TDateField;
          QAlunoALUSENHA: TStringField;
          CDSAlunoALUSENHA: TStringField;
          QAlunoALUMONOTITULO: TStringField;
          CDSAlunoALUMONOTITULO: TStringField;
          CDSLctoContabilLCTORIGEM: TIntegerField;
          CDSNovo1: TClientDataSet;
          CDSNovo2: TClientDataSet;
          CDSNovo3: TClientDataSet;
          CDSNovo4: TClientDataSet;
          CDSNovo5: TClientDataSet;
          QAlunoALUENTREGOUDIPLOMA: TStringField;
          QAlunoALUENTREGOUCPF: TStringField;
          QAlunoALUENTREGOURG: TStringField;
          CDSAlunoALUENTREGOUDIPLOMA: TStringField;
          CDSAlunoALUENTREGOUCPF: TStringField;
          CDSAlunoALUENTREGOURG: TStringField;
          QProfessorPROVINCULO: TStringField;
          CDSProfessorPROVINCULO: TStringField;
          QContabil: TSQLQuery;
          CDSContabil: TClientDataSet;
          DSPContabil: TDataSetProvider;
          DSContabil: TDataSource;
          QContabilCONCOD: TIntegerField;
          QContabilCONMENSDEBITO: TStringField;
          QContabilCONMENSCREDITO: TStringField;
          QContabilCONMENSHISTPADRAO: TIntegerField;
          QContabilCONDESCDEBITO: TStringField;
          QContabilCONDESCCREDITO: TStringField;
          QContabilCONDESCHISTPADRAO: TIntegerField;
          QContabilCONJURODEBITO: TStringField;
          QContabilCONJUROCREDITO: TStringField;
          QContabilCONJUROHISTPADRAO: TIntegerField;
          CDSContabilCONCOD: TIntegerField;
          CDSContabilCONMENSDEBITO: TStringField;
          CDSContabilCONMENSCREDITO: TStringField;
          CDSContabilCONMENSHISTPADRAO: TIntegerField;
          CDSContabilCONDESCDEBITO: TStringField;
          CDSContabilCONDESCCREDITO: TStringField;
          CDSContabilCONDESCHISTPADRAO: TIntegerField;
          CDSContabilCONJURODEBITO: TStringField;
          CDSContabilCONJUROCREDITO: TStringField;
          CDSContabilCONJUROHISTPADRAO: TIntegerField;
          QAlunoDisciplinaALUDISNOTA: TFloatField;
          QAlunoDisciplinaData: TSQLQuery;
          CDSAlunoDisciplinaData: TClientDataSet;
          DSAlunoDisciplinaData: TDataSource;
          QAlunoDisciplinaDataALUDISDATAALUNO: TIntegerField;
          QAlunoDisciplinaDataALUDISDATADISCIPLINA: TIntegerField;
          QAlunoDisciplinaDataALUDISDATAPROFESSOR: TIntegerField;
          QAlunoDisciplinaDataALUDISDATADATA: TDateField;
          QAlunoDisciplinaDataALUDISDATAINICIO: TStringField;
          QAlunoDisciplinaDataALUDISDATAFIM: TStringField;
          CDSAlunoDisciplinaDataALUDISDATAALUNO: TIntegerField;
          CDSAlunoDisciplinaDataALUDISDATADISCIPLINA: TIntegerField;
          CDSAlunoDisciplinaDataALUDISDATAPROFESSOR: TIntegerField;
          CDSAlunoDisciplinaDataALUDISDATADATA: TDateField;
          CDSAlunoDisciplinaDataALUDISDATAINICIO: TStringField;
          CDSAlunoDisciplinaDataALUDISDATAFIM: TStringField;
          QCursoDisciplinaData: TSQLQuery;
          CDSCursoDisciplinaData: TClientDataSet;
          DSCursoDisciplinaData: TDataSource;
          QCursoDisciplinaDataCURDISDATACURSO: TIntegerField;
          QCursoDisciplinaDataCURDISDATADISCIPLINA: TIntegerField;
          QCursoDisciplinaDataCURDISDATAPROFESSOR: TIntegerField;
          QCursoDisciplinaDataCURDISDATADATA: TDateField;
          QCursoDisciplinaDataCURDISDATAINICIO: TStringField;
          QCursoDisciplinaDataCURDISDATAFIM: TStringField;
          CDSCursoDisciplinaDataCURDISDATACURSO: TIntegerField;
          CDSCursoDisciplinaDataCURDISDATADISCIPLINA: TIntegerField;
          CDSCursoDisciplinaDataCURDISDATAPROFESSOR: TIntegerField;
          CDSCursoDisciplinaDataCURDISDATADATA: TDateField;
          CDSCursoDisciplinaDataCURDISDATAINICIO: TStringField;
          CDSCursoDisciplinaDataCURDISDATAFIM: TStringField;
          QMensalidadeMENRECEBEU: TStringField;
          CDSMensalidadeMENRECEBEU: TStringField;
          QMensalidadeMENBOLSA: TFloatField;
          CDSMensalidadeMENBOLSA: TFloatField;
          QAlunoDisciplinaALUDISHA: TIntegerField;
          CDSAlunoDisciplinaALUDISHA: TIntegerField;
          QInstitutoINSDATAENCCONTABIL: TDateField;
          CDSInstitutoINSDATAENCCONTABIL: TDateField;
          QFormaPgtoFORTIPO: TStringField;
          CDSFormaPgtoFORTIPO: TStringField;
          QContabilCONMENSDEBITOBANCO: TStringField;
          QContabilCONMENSCREDITOBANCO: TStringField;
          QContabilCONDESCDEBITOBANCO: TStringField;
          QContabilCONDESCCREDITOBANCO: TStringField;
          QContabilCONJURODEBITOBANCO: TStringField;
          QContabilCONJUROCREDITOBANCO: TStringField;
          CDSContabilCONMENSDEBITOBANCO: TStringField;
          CDSContabilCONMENSCREDITOBANCO: TStringField;
          CDSContabilCONDESCDEBITOBANCO: TStringField;
          CDSContabilCONDESCCREDITOBANCO: TStringField;
          CDSContabilCONJURODEBITOBANCO: TStringField;
          CDSContabilCONJUROCREDITOBANCO: TStringField;
          QAlunoMensalidadeMENBOLSA: TFloatField;
          QAlunoMensalidadeMENACRESCIMO: TFloatField;
          CDSAlunoMensalidadeMENBOLSA: TFloatField;
          CDSAlunoMensalidadeMENACRESCIMO: TFloatField;
          QMensalidadeMENLIQUIDO: TFloatField;
          CDSMensalidadeMENLIQUIDO: TFloatField;
          QMensalidadeMENTIPO: TStringField;
          CDSMensalidadeMENTIPO: TStringField;
          QCursoCURSIGLA: TStringField;
          CDSCursoCURSIGLA: TStringField;
          QAlunoDisciplinaALUDISLANCADO: TStringField;
          CDSAlunoDisciplinaALUDISLANCADO: TStringField;
          QDreItem: TSQLQuery;
          CDSDre: TClientDataSet;
          QDre: TSQLQuery;
          CDSDreItem: TClientDataSet;
          DSDreItem: TDataSource;
          DSDre: TDataSource;
          DSPDre: TDataSetProvider;
          QDreConta: TSQLQuery;
          CDSDreConta: TClientDataSet;
          DSDreConta: TDataSource;
          QDreDRECOD: TIntegerField;
          QDreDRENOME: TStringField;
          CDSDreDRECOD: TIntegerField;
          CDSDreDRENOME: TStringField;
          QDreItemDREITEDRE: TIntegerField;
          QDreItemDREITECOD: TIntegerField;
          QDreItemDREITENOME: TStringField;
          CDSDreItemDREITEDRE: TIntegerField;
          CDSDreItemDREITECOD: TIntegerField;
          CDSDreItemDREITENOME: TStringField;
          QDreContaDRECONDRE: TIntegerField;
          QDreContaDRECONITEM: TIntegerField;
          QDreContaDRECONCONTA: TStringField;
          QDreContaDRECONOPERACAO: TStringField;
          CDSDreContaDRECONDRE: TIntegerField;
          CDSDreContaDRECONITEM: TIntegerField;
          CDSDreContaDRECONCONTA: TStringField;
          CDSDreContaDRECONOPERACAO: TStringField;
          CDSDreContaConta: TStringField;
          QDreItemDREITEOPERACAO: TStringField;
          QDreItemDREITEDESTACAR: TStringField;
          CDSDreItemDREITEOPERACAO: TStringField;
          CDSDreItemDREITEDESTACAR: TStringField;
          QParamEmpEMPCEP: TStringField;
          QParamEmpEMPIM: TStringField;
          QParamEmpEMPDIRETOR: TStringField;
          QParamEmpEMPDIRETORCPF: TStringField;
          QParamEmpEMPDIRETORIDENTIDADE: TStringField;
          QParamEmpEMPOBS: TStringField;
          QParamEmpEMPATIVIDADE: TStringField;
          CDSParamEmpEMPCEP: TStringField;
          CDSParamEmpEMPIM: TStringField;
          CDSParamEmpEMPDIRETOR: TStringField;
          CDSParamEmpEMPDIRETORCPF: TStringField;
          CDSParamEmpEMPDIRETORIDENTIDADE: TStringField;
          CDSParamEmpEMPOBS: TStringField;
          CDSParamEmpEMPATIVIDADE: TStringField;
          QUsuarioUSUNAOINCLUI: TStringField;
          QUsuarioUSUNAOALTERA: TStringField;
          QUsuarioUSUNAOEXCLUI: TStringField;
          QUsuarioUSUNAOCONSULTA: TStringField;
          CDSUsuarioUSUNAOINCLUI: TStringField;
          CDSUsuarioUSUNAOALTERA: TStringField;
          CDSUsuarioUSUNAOEXCLUI: TStringField;
          CDSUsuarioUSUNAOCONSULTA: TStringField;
          CDSAlunoMensalidadeValor: TAggregateField;
          CDSAlunoMensalidadeDesconto: TAggregateField;
          CDSAlunoMensalidadeBolsa: TAggregateField;
          CDSAlunoMensalidadeAcrescimo: TAggregateField;
          CDSAlunoMensalidadeValorPago: TAggregateField;
          CDSAlunoMensalidadeLiquido: TAggregateField;
          CDSTemp: TClientDataSet;
          QMensalidadeBANNOME: TStringField;
          CDSMensalidadeBANNOME: TStringField;
          QBancoBANFORMAPGTO: TIntegerField;
          CDSBancoBANFORMAPGTO: TIntegerField;
          CDSBancoformapgto: TStringField;
          CDSLctoContabilLCTEXCLUI: TStringField;
          CDSLctoContabilLCTPASSOU: TStringField;
          CDSLctoContabilLCTDOCUMENTO: TIntegerField;
          QUsuarioUSUCOORDENADOR: TStringField;
          CDSUsuarioUSUCOORDENADOR: TStringField;
          QAlunoALUBOLSA: TIntegerField;
          CDSAlunoALUBOLSA: TIntegerField;
          QAlunoALUEMAILALT: TStringField;
          CDSAlunoALUEMAILALT: TStringField;
          QAlunoALUALTERAR: TStringField;
          CDSAlunoALUALTERAR: TStringField;
          QMensalidadeMENDOCUMENTO: TStringField;
          CDSMensalidadeMENDOCUMENTO: TStringField;
          QProfessorPROEMAIL2: TStringField;
          QProfessorPROFORMACAO: TStringField;
          CDSProfessorPROEMAIL2: TStringField;
          CDSProfessorPROFORMACAO: TStringField;
          QInstitutoINSIE: TStringField;
          QInstitutoINSIM: TStringField;
          QInstitutoINSRAZAO: TStringField;
          QInstitutoINSNUMERO: TIntegerField;
          QInstitutoINSCEP: TStringField;
          QInstitutoINSUF: TStringField;
          CDSInstitutoINSIE: TStringField;
          CDSInstitutoINSIM: TStringField;
          CDSInstitutoINSRAZAO: TStringField;
          CDSInstitutoINSNUMERO: TIntegerField;
          CDSInstitutoINSCEP: TStringField;
          CDSInstitutoINSUF: TStringField;
          QInstitutoINSATIVIDADE: TStringField;
          QInstitutoINSOBS: TStringField;
          QInstitutoINSDIRETORIDENTIDADE: TStringField;
          QInstitutoINSDIRETORCPF: TStringField;
          QInstitutoINSDIRETOR: TStringField;
          CDSInstitutoINSATIVIDADE: TStringField;
          CDSInstitutoINSOBS: TStringField;
          CDSInstitutoINSDIRETORIDENTIDADE: TStringField;
          CDSInstitutoINSDIRETORCPF: TStringField;
          CDSInstitutoINSDIRETOR: TStringField;
          QUsuarioUSUMENU: TStringField;
          CDSUsuarioUSUMENU: TStringField;
          QMensalidadeALUSITUACAO: TStringField;
          CDSMensalidadeALUSITUACAO: TStringField;
          CDSNetworking: TClientDataSet;
          DSPNetworking: TDataSetProvider;
          QNetworking: TSQLQuery;
          DSNetworking: TDataSource;
          QNetworkingNETCOD: TIntegerField;
          QNetworkingNETNOME: TStringField;
          QNetworkingNETENDERECO: TStringField;
          QNetworkingNETBAIRRO: TStringField;
          QNetworkingNETCIDADE: TIntegerField;
          QNetworkingNETCEP: TStringField;
          QNetworkingNETFONE: TStringField;
          QNetworkingNETFAX: TStringField;
          QNetworkingNETCELULAR: TStringField;
          QNetworkingNETEMAIL: TStringField;
          QNetworkingNETSITE: TStringField;
          QNetworkingNETCPF: TStringField;
          QNetworkingNETRESUMO: TStringField;
          QNetworkingNETOBS: TMemoField;
          QNetworkingNETEMAIL2: TStringField;
          CDSNetworkingNETCOD: TIntegerField;
          CDSNetworkingNETNOME: TStringField;
          CDSNetworkingNETENDERECO: TStringField;
          CDSNetworkingNETBAIRRO: TStringField;
          CDSNetworkingNETCIDADE: TIntegerField;
          CDSNetworkingNETCEP: TStringField;
          CDSNetworkingNETFONE: TStringField;
          CDSNetworkingNETFAX: TStringField;
          CDSNetworkingNETCELULAR: TStringField;
          CDSNetworkingNETEMAIL: TStringField;
          CDSNetworkingNETSITE: TStringField;
          CDSNetworkingNETCPF: TStringField;
          CDSNetworkingNETRESUMO: TStringField;
          CDSNetworkingNETOBS: TMemoField;
          CDSNetworkingNETEMAIL2: TStringField;
          CDSNetworkingcidade: TStringField;
          QNetworkingNETEMPRESA: TStringField;
          QNetworkingNETCONTATO: TStringField;
          CDSNetworkingNETEMPRESA: TStringField;
          CDSNetworkingNETCONTATO: TStringField;
          QAlunoALUNEGFINANCEIRA: TMemoField;
          CDSAlunoALUNEGFINANCEIRA: TMemoField;
          QAlunoDisciplinaALUDISDATA: TDateField;
          CDSAlunoDisciplinaALUDISDATA: TDateField;
          QAlunoLancALUDISDATA: TDateField;
          CDSAlunoLancALUDISDATA: TDateField;
          CDSAlunoLancprofessor: TStringField;
          QOrcamento: TSQLQuery;
          CDSOrcamento: TClientDataSet;
          DSPOrcamento: TDataSetProvider;
          DSOrcamento: TDataSource;
          QOrcamentoORCNUMERO: TIntegerField;
          QOrcamentoORCDATA: TDateField;
          QOrcamentoORCCONTA: TStringField;
          QOrcamentoORCHISTPADRAO: TIntegerField;
          QOrcamentoORCHISTCOMPLEMENTO: TStringField;
          QOrcamentoORCVALOR: TFloatField;
          QOrcamentoCONTA: TStringField;
          CDSOrcamentoORCNUMERO: TIntegerField;
          CDSOrcamentoORCDATA: TDateField;
          CDSOrcamentoORCCONTA: TStringField;
          CDSOrcamentoORCHISTPADRAO: TIntegerField;
          CDSOrcamentoORCHISTCOMPLEMENTO: TStringField;
          CDSOrcamentoORCVALOR: TFloatField;
          CDSOrcamentoCONTA: TStringField;
          CDSOrcamentohistpadrao: TStringField;
          CDSOrcamentocontalkp: TStringField;
          QMensalidadeMENBOLETOIMPRESSO: TStringField;
          CDSMensalidadeMENBOLETOIMPRESSO: TStringField;
          QFormaPgtoFORCONTAVALORDEBITO: TStringField;
          QFormaPgtoFORCONTAVALORCREDITO: TStringField;
          QFormaPgtoFORCONTADESCONTODEBITO: TStringField;
          QFormaPgtoFORCONTADESCONTOCREDITO: TStringField;
          QFormaPgtoFORCONTAJUROCREDITO: TStringField;
          QFormaPgtoFORCONTAJURODEBITO: TStringField;
          QFormaPgtoFORHISTPADRAOVALOR: TIntegerField;
          QFormaPgtoFORHISTPADRAODESCONTO: TIntegerField;
          QFormaPgtoFORHISTPADRAOJURO: TIntegerField;
          CDSFormaPgtoFORCONTAVALORDEBITO: TStringField;
          CDSFormaPgtoFORCONTAVALORCREDITO: TStringField;
          CDSFormaPgtoFORCONTADESCONTODEBITO: TStringField;
          CDSFormaPgtoFORCONTADESCONTOCREDITO: TStringField;
          CDSFormaPgtoFORCONTAJUROCREDITO: TStringField;
          CDSFormaPgtoFORCONTAJURODEBITO: TStringField;
          CDSFormaPgtoFORHISTPADRAOVALOR: TIntegerField;
          CDSFormaPgtoFORHISTPADRAODESCONTO: TIntegerField;
          CDSFormaPgtoFORHISTPADRAOJURO: TIntegerField;
          CDSFormaPgtoValorDebito: TStringField;
          CDSFormaPgtoValorCredito: TStringField;
          CDSFormaPgtoDescontoDebito: TStringField;
          CDSFormaPgtoDescontoCredito: TStringField;
          CDSFormaPgtoJuroCredito: TStringField;
          CDSFormaPgtoJuroDebito: TStringField;
          CDSFormaPgtoHistValor: TStringField;
          CDSFormaPgtoHistDesconto: TStringField;
          CDSFormaPgtoHistJuro: TStringField;
          QCursoCURSITE: TStringField;
          QCursoCURSITEMONOGRAFIA: TStringField;
          CDSCursoCURSITE: TStringField;
          CDSCursoCURSITEMONOGRAFIA: TStringField;
          QPlanoContaPLANIVEL1: TStringField;
          QPlanoContaPLANIVEL2: TStringField;
          QPlanoContaPLANIVEL3: TStringField;
          QPlanoContaPLANIVEL4: TStringField;
          QPlanoContaPLANIVEL5: TStringField;
          QPlanoContaPLANIVEL6: TStringField;
          QPlanoContaPLANIVEL7: TStringField;
          QPlanoContaPLANIVEL8: TStringField;
          QPlanoContaPLANIVEL9: TStringField;
          QPlanoContaPLANIVEL10: TStringField;
          CDSPlanoContaPLANIVEL1: TStringField;
          CDSPlanoContaPLANIVEL2: TStringField;
          CDSPlanoContaPLANIVEL3: TStringField;
          CDSPlanoContaPLANIVEL4: TStringField;
          CDSPlanoContaPLANIVEL5: TStringField;
          CDSPlanoContaPLANIVEL6: TStringField;
          CDSPlanoContaPLANIVEL7: TStringField;
          CDSPlanoContaPLANIVEL8: TStringField;
          CDSPlanoContaPLANIVEL9: TStringField;
          CDSPlanoContaPLANIVEL10: TStringField;
          QMensalidadeMENRENEGOCIACAO: TStringField;
          CDSMensalidadeMENRENEGOCIACAO: TStringField;
          CDSServicosFin: TClientDataSet;
          DSPServicosFin: TDataSetProvider;
          QServicosFin: TSQLQuery;
          DSServicosFin: TDataSource;
          QLctoContabilLCTNUMERO: TIntegerField;
          QLctoContabilLCTDATA: TDateField;
          QLctoContabilLCTDEBITO: TStringField;
          QLctoContabilLCTCREDITO: TStringField;
          QLctoContabilLCTHISTPADRAO: TIntegerField;
          QLctoContabilLCTPLANONEGOCIOS: TIntegerField;
          QLctoContabilLCTVALOR: TFloatField;
          QLctoContabilLCTORIGEM: TIntegerField;
          QLctoContabilCONTACREDITO: TStringField;
          QLctoContabilCONTADEBITO: TStringField;
          QLctoContabilLCTDOCUMENTO: TIntegerField;
          QLctoContabilLCTEXCLUI: TStringField;
          QLctoContabilLCTPASSOU: TStringField;
          QServicosFinFINCOD: TIntegerField;
          QServicosFinFINDESCRICAO: TStringField;
          QServicosFinFINSITE: TStringField;
          QServicosFinFINTELEFONE: TStringField;
          QServicosFinFINOBSERVACAO: TStringField;
          CDSServicosFinFINCOD: TIntegerField;
          CDSServicosFinFINDESCRICAO: TStringField;
          CDSServicosFinFINSITE: TStringField;
          CDSServicosFinFINTELEFONE: TStringField;
          CDSServicosFinFINOBSERVACAO: TStringField;
          QProfessorPROIDENTIDADE: TStringField;
          CDSProfessorPROIDENTIDADE: TStringField;
          CDSAlunoLkp: TClientDataSet;
          DSPAlunoLkp: TDataSetProvider;
          QAlunoLkp: TSQLQuery;
          DSAlunoLkp: TDataSource;
          QUsuarioUSUENDERECO: TStringField;
          QUsuarioUSUBAIRRO: TStringField;
          QUsuarioUSUCIDADE: TIntegerField;
          QUsuarioUSUCEP: TStringField;
          QUsuarioUSUFONE: TStringField;
          QUsuarioUSUFAX: TStringField;
          QUsuarioUSUCELULAR: TStringField;
          QUsuarioUSUEMAIL: TStringField;
          QUsuarioUSUCPF: TStringField;
          QUsuarioUSUIDENTIDADE: TStringField;
          QUsuarioUSUCARTEIRA: TStringField;
          QUsuarioUSUOCORRENCIAS: TMemoField;
          QUsuarioUSUHISTESCOLAR: TMemoField;
          QUsuarioUSUNACIONALIDADE: TStringField;
          QUsuarioUSUNASCIMENTO: TDateField;
          QUsuarioUSUNATURALIDADE: TIntegerField;
          QUsuarioUSUSITUACAO: TStringField;
          QUsuarioUSUESTADOCIVIL: TStringField;
          QUsuarioUSUORGAOEXPEDIDOR: TStringField;
          QUsuarioUSUDATAEXPEDICAO: TDateField;
          QUsuarioUSUSEXO: TStringField;
          QUsuarioUSUNOMEMAE: TStringField;
          QUsuarioUSUNOMEPAI: TStringField;
          CDSUsuarioUSUENDERECO: TStringField;
          CDSUsuarioUSUBAIRRO: TStringField;
          CDSUsuarioUSUCIDADE: TIntegerField;
          CDSUsuarioUSUCEP: TStringField;
          CDSUsuarioUSUFONE: TStringField;
          CDSUsuarioUSUFAX: TStringField;
          CDSUsuarioUSUCELULAR: TStringField;
          CDSUsuarioUSUEMAIL: TStringField;
          CDSUsuarioUSUCPF: TStringField;
          CDSUsuarioUSUIDENTIDADE: TStringField;
          CDSUsuarioUSUCARTEIRA: TStringField;
          CDSUsuarioUSUOCORRENCIAS: TMemoField;
          CDSUsuarioUSUHISTESCOLAR: TMemoField;
          CDSUsuarioUSUNACIONALIDADE: TStringField;
          CDSUsuarioUSUNASCIMENTO: TDateField;
          CDSUsuarioUSUNATURALIDADE: TIntegerField;
          CDSUsuarioUSUSITUACAO: TStringField;
          CDSUsuarioUSUESTADOCIVIL: TStringField;
          CDSUsuarioUSUORGAOEXPEDIDOR: TStringField;
          CDSUsuarioUSUDATAEXPEDICAO: TDateField;
          CDSUsuarioUSUSEXO: TStringField;
          CDSUsuarioUSUNOMEMAE: TStringField;
          CDSUsuarioUSUNOMEPAI: TStringField;
          QAlunoServicoFin: TSQLQuery;
          CDSAlunoServicoFin: TClientDataSet;
          DSAlunoServicoFin: TDataSource;
          QAlunoServicoFinALUSERFINALUNO: TIntegerField;
          QAlunoServicoFinALUSERFINCODIGO: TIntegerField;
          QAlunoServicoFinALUSERFINDATA: TDateField;
          QAlunoServicoFinALUSERFINSERVICOFIN: TIntegerField;
          QAlunoServicoFinALUSERFINHISTORICO: TStringField;
          QAlunoServicoFinALUSERFINUSUARIO: TStringField;
          QAlunoServicoFinFINDESCRICAO: TStringField;
          CDSAlunoServicoFinALUSERFINALUNO: TIntegerField;
          CDSAlunoServicoFinALUSERFINCODIGO: TIntegerField;
          CDSAlunoServicoFinALUSERFINDATA: TDateField;
          CDSAlunoServicoFinALUSERFINSERVICOFIN: TIntegerField;
          CDSAlunoServicoFinALUSERFINHISTORICO: TStringField;
          CDSAlunoServicoFinALUSERFINUSUARIO: TStringField;
          CDSAlunoServicoFinFINDESCRICAO: TStringField;
          QLctoContabilLCTIDENTIFICADOR: TIntegerField;
          QLctoContabilIDENOME: TStringField;
          CDSLctoContabilLCTIDENTIFICADOR: TIntegerField;
          CDSLctoContabilIDENOME: TStringField;
          CDSIdentificador: TClientDataSet;
          DSPIdentificador: TDataSetProvider;
          QIdentificador: TSQLQuery;
          DSIdentificador: TDataSource;
          QIdentificadorIDECOD: TIntegerField;
          QIdentificadorIDENOME: TStringField;
          CDSIdentificadorIDECOD: TIntegerField;
          CDSIdentificadorIDENOME: TStringField;
          CDSLctoContabilidentificador: TStringField;
          CDSLctoContabilLCTIDENTIFICADORCOMPLEMENTO: TStringField;
          QLctoContabilLCTIDENTIFICADORCOMPLEMENTO: TStringField;
          QNetworkingNETSITE2: TStringField;
          QNetworkingNETIE: TStringField;
          QNetworkingNETIM: TStringField;
          QNetworkingNETORGAONOME1: TStringField;
          QNetworkingNETORGAONUMERO1: TStringField;
          QNetworkingNETORGAONOME2: TStringField;
          QNetworkingNETORGAONUMERO2: TStringField;
          QNetworkingNETORGAONOME3: TStringField;
          QNetworkingNETORGAONUMERO3: TStringField;
          QNetworkingNETCONTATO1: TStringField;
          QNetworkingNETCONTATOFONE1: TStringField;
          QNetworkingNETCONTATO2: TStringField;
          QNetworkingNETCONTATOFONE2: TStringField;
          QNetworkingNETCONTATO3: TStringField;
          QNetworkingNETCONTATOFONE3: TStringField;
          QNetworkingNETESPECIALIDADES: TMemoField;
          QNetworkingNETINFESPECIAIS: TMemoField;
          CDSNetworkingNETSITE2: TStringField;
          CDSNetworkingNETIE: TStringField;
          CDSNetworkingNETIM: TStringField;
          CDSNetworkingNETORGAONOME1: TStringField;
          CDSNetworkingNETORGAONUMERO1: TStringField;
          CDSNetworkingNETORGAONOME2: TStringField;
          CDSNetworkingNETORGAONUMERO2: TStringField;
          CDSNetworkingNETORGAONOME3: TStringField;
          CDSNetworkingNETORGAONUMERO3: TStringField;
          CDSNetworkingNETCONTATO1: TStringField;
          CDSNetworkingNETCONTATOFONE1: TStringField;
          CDSNetworkingNETCONTATO2: TStringField;
          CDSNetworkingNETCONTATOFONE2: TStringField;
          CDSNetworkingNETCONTATO3: TStringField;
          CDSNetworkingNETCONTATOFONE3: TStringField;
          CDSNetworkingNETESPECIALIDADES: TMemoField;
          CDSNetworkingNETINFESPECIAIS: TMemoField;
          QNetworkingNETPESSOA: TStringField;
          CDSNetworkingNETPESSOA: TStringField;
          QNetworkingNETRAMOPRI: TStringField;
          CDSNetworkingNETRAMOPRI: TStringField;
          QNetworkingNETRAMOSEC: TStringField;
          QNetworkingNETDATAFUND: TDateField;
          QNetworkingNETJUNTACOMERC: TStringField;
          CDSNetworkingNETRAMOSEC: TStringField;
          CDSNetworkingNETDATAFUND: TDateField;
          CDSNetworkingNETJUNTACOMERC: TStringField;
          QProfessorDisciplinaPRODISPESQUISA: TStringField;
          CDSProfessorDisciplinaPRODISPESQUISA: TStringField;
          QCursoCURSITECALENDARIO: TStringField;
          QCursoCURSITEAVISO: TStringField;
          CDSCursoCURSITECALENDARIO: TStringField;
          CDSCursoCURSITEAVISO: TStringField;
          CDSCidadeCIDCEP: TStringField;
          QCidadeCIDCEP: TStringField;
          QProfessorPRODADOSFIN: TMemoField;
          CDSProfessorPRODADOSFIN: TMemoField;
          QAlunoALUEGRESSO: TMemoField;
          CDSAlunoALUEGRESSO: TMemoField;
          QAlunoALUDATAPENDMONO: TDateField;
          CDSAlunoALUDATAPENDMONO: TDateField;
          QAlunoALURESPONSAVEL: TStringField;
          QAlunoALURESPONSAVELCPF: TStringField;
          CDSAlunoALURESPONSAVEL: TStringField;
          CDSAlunoALURESPONSAVELCPF: TStringField;
          QCursoCURHORARIO: TStringField;
          CDSCursoCURHORARIO: TStringField;
          QDisciplinaDISVALOR: TFloatField;
          CDSDisciplinaDISVALOR: TFloatField;
          QMensalidadeMENPROFESSOR: TIntegerField;
          CDSMensalidadeMENPROFESSOR: TIntegerField;
          QDisciplinaDISVALORPROFESSOR: TFloatField;
          CDSDisciplinaDISVALORPROFESSOR: TFloatField;
          QCursoCURNUMTURMA: TIntegerField;
          CDSCursoCURNUMTURMA: TIntegerField;
          QMensalidadeMENDISCIPLINA: TIntegerField;
          CDSMensalidadeMENDISCIPLINA: TIntegerField;
          DSExec: TDataSource;
          QAutor: TSQLQuery;
          CDSAutor: TClientDataSet;
          DSPAutor: TDataSetProvider;
          DSAutor: TDataSource;
          QAutorAUTCOD: TIntegerField;
          QAutorAUTNOME: TStringField;
          CDSAutorAUTCOD: TIntegerField;
          CDSAutorAUTNOME: TStringField;
          QEditora: TSQLQuery;
          CDSEditora: TClientDataSet;
          DSPEditora: TDataSetProvider;
          DSEditora: TDataSource;
          QEditoraEDICOD: TIntegerField;
          QEditoraEDINOME: TStringField;
          CDSEditoraEDICOD: TIntegerField;
          CDSEditoraEDINOME: TStringField;
    QAssunto: TSQLQuery;
    CDSAssunto: TClientDataSet;
    DSPAssunto: TDataSetProvider;
    DSAssunto: TDataSource;
    QTipoMaterial: TSQLQuery;
    CDSTipoMaterial: TClientDataSet;
    DSPTipoMaterial: TDataSetProvider;
    DSTipoMaterial: TDataSource;
    QAssuntoASSCOD: TIntegerField;
    QAssuntoASSNOME: TStringField;
    CDSAssuntoASSCOD: TIntegerField;
    CDSAssuntoASSNOME: TStringField;
    QTipoMaterialTIPMATNOME: TStringField;
    QTipoMaterialTIPMATCOD: TIntegerField;
    CDSTipoMaterialTIPMATCOD: TIntegerField;
    CDSTipoMaterialTIPMATNOME: TStringField;
    QMensalidadeMENVALORPROFESSOR: TFloatField;
    CDSMensalidadeMENVALORPROFESSOR: TFloatField;
    CDSAlunoFoto: TClientDataSet;
    DSPAlunoFoto: TDataSetProvider;
    QAlunoFoto: TSQLQuery;
    DSAlunoFoto: TDataSource;
    QAlunoFotoALUCOD: TIntegerField;
    QAlunoFotoALUFOTO: TBlobField;
    CDSAlunoFotoALUCOD: TIntegerField;
    CDSAlunoFotoALUFOTO: TBlobField;
    CDSMaterial: TClientDataSet;
    DSPMaterial: TDataSetProvider;
    QMaterial: TSQLQuery;
    DSMaterial: TDataSource;
    QMaterialAssunto: TSQLQuery;
    CDSMaterialAssunto: TClientDataSet;
    DSMaterialAssunto: TDataSource;
    QMaterialAutor: TSQLQuery;
    CDSMaterialAutor: TClientDataSet;
    DSMaterialAutor: TDataSource;
    QMaterialMATCOD: TIntegerField;
    QMaterialMATTIPO: TIntegerField;
    QMaterialMATREFERENCIA: TStringField;
    QMaterialMATTITULO: TStringField;
    QMaterialMATEDITORA: TIntegerField;
    QMaterialMATCDU: TStringField;
    QMaterialMATCUTTER: TStringField;
    QMaterialMATLOCAL: TStringField;
    QMaterialMATANOPUBLICACAO: TIntegerField;
    QMaterialMATEDICAO: TStringField;
    QMaterialMATSERIE: TStringField;
    QMaterialMATTIPODOLIVRO: TStringField;
    QMaterialMATPAGINAARTIGO: TStringField;
    QMaterialMATPAGINAS: TIntegerField;
    QMaterialMATPERIODICIDADE: TStringField;
    QMaterialMATISSN: TStringField;
    QMaterialMATSITUACAO: TStringField;
    QMaterialMATNUMEROEXEMPLARES: TIntegerField;
    QMaterialMATNUMEROVOLUMES: TIntegerField;
    QMaterialMATIDIOMA: TStringField;
    QMaterialMATDATAATUALIZACAO: TSQLTimeStampField;
    QMaterialMATOBSERVACAO: TStringField;
    CDSMaterialMATCOD: TIntegerField;
    CDSMaterialMATTIPO: TIntegerField;
    CDSMaterialMATREFERENCIA: TStringField;
    CDSMaterialMATTITULO: TStringField;
    CDSMaterialMATEDITORA: TIntegerField;
    CDSMaterialMATCDU: TStringField;
    CDSMaterialMATCUTTER: TStringField;
    CDSMaterialMATLOCAL: TStringField;
    CDSMaterialMATANOPUBLICACAO: TIntegerField;
    CDSMaterialMATEDICAO: TStringField;
    CDSMaterialMATSERIE: TStringField;
    CDSMaterialMATTIPODOLIVRO: TStringField;
    CDSMaterialMATPAGINAARTIGO: TStringField;
    CDSMaterialMATPAGINAS: TIntegerField;
    CDSMaterialMATPERIODICIDADE: TStringField;
    CDSMaterialMATISSN: TStringField;
    CDSMaterialMATSITUACAO: TStringField;
    CDSMaterialMATNUMEROEXEMPLARES: TIntegerField;
    CDSMaterialMATNUMEROVOLUMES: TIntegerField;
    CDSMaterialMATIDIOMA: TStringField;
    CDSMaterialMATDATAATUALIZACAO: TSQLTimeStampField;
    CDSMaterialMATOBSERVACAO: TStringField;
    QMaterialAutorMATAUTMATERIAL: TIntegerField;
    QMaterialAutorMATAUTAUTOR: TIntegerField;
    CDSMaterialAutorMATAUTMATERIAL: TIntegerField;
    CDSMaterialAutorMATAUTAUTOR: TIntegerField;
    CDSMaterialAutorautor: TStringField;
    QMaterialAssuntoMATASSMATERIAL: TIntegerField;
    QMaterialAssuntoMATASSASSUNTO: TIntegerField;
    CDSMaterialAssuntoMATASSMATERIAL: TIntegerField;
    CDSMaterialAssuntoMATASSASSUNTO: TIntegerField;
    CDSMaterialAssuntoAssunto: TStringField;
    CDSMaterialeditora: TStringField;
    QMaterialMATVALOR: TFloatField;
    QMaterialMATFORNECEDOR: TIntegerField;
    QMaterialMATAQUISICAO: TDateField;
    QMaterialMATPRATELEIRA: TStringField;
    CDSMaterialMATVALOR: TFloatField;
    CDSMaterialMATFORNECEDOR: TIntegerField;
    CDSMaterialMATAQUISICAO: TDateField;
    CDSMaterialMATPRATELEIRA: TStringField;
    CDSMaterialfornecedor: TStringField;
    QTransito: TSQLQuery;
    CDSTransito: TClientDataSet;
    DSPTransito: TDataSetProvider;
    DSTransito: TDataSource;
    QTransitoTRACOD: TIntegerField;
    QTransitoTRARETIRADA: TDateField;
    QTransitoTRADEVOLUCAO: TDateField;
    QTransitoTRAENTREGA: TDateField;
    QTransitoTRAALUNO: TIntegerField;
    QTransitoTRAMATERIAL: TIntegerField;
    QTransitoTRAMULTA: TFloatField;
    QTransitoTRAPAGO: TStringField;
    QTransitoTRAUSUARIOBAIXA: TStringField;
    QTransitoTRAOBSERVACAO: TStringField;
    CDSTransitoTRACOD: TIntegerField;
    CDSTransitoTRARETIRADA: TDateField;
    CDSTransitoTRADEVOLUCAO: TDateField;
    CDSTransitoTRAENTREGA: TDateField;
    CDSTransitoTRAALUNO: TIntegerField;
    CDSTransitoTRAMATERIAL: TIntegerField;
    CDSTransitoTRAMULTA: TFloatField;
    CDSTransitoTRAPAGO: TStringField;
    CDSTransitoTRAUSUARIOBAIXA: TStringField;
    CDSTransitoTRAOBSERVACAO: TStringField;
    CDSTransitoAluno: TStringField;
    CDSTransitoMaterial: TStringField;
    QTransitoTRARESERVA: TStringField;
    CDSTransitoTRARESERVA: TStringField;
    QContaPagar: TSQLQuery;
    CDSContaPagar: TClientDataSet;
    DSPContaPagar: TDataSetProvider;
    DSContaPagar: TDataSource;
    QContaPagarCTPCOD: TIntegerField;
    QContaPagarCTPFORNECEDOR: TIntegerField;
    QContaPagarCTPTIPOCONTA: TStringField;
    QContaPagarCTPCADASTRO: TDateField;
    QContaPagarCTPEMISSAO: TDateField;
    QContaPagarCTPVENCIMENTO: TDateField;
    QContaPagarCTPLIQUIDACAO: TDateField;
    QContaPagarCTPDOCUMENTO: TIntegerField;
    QContaPagarCTPSERIE: TStringField;
    QContaPagarCTPBANCO: TIntegerField;
    QContaPagarCTPVALOR: TFloatField;
    QContaPagarCTPSALDO: TFloatField;
    QContaPagarCTPJURO: TFloatField;
    QContaPagarCTPMULTA: TFloatField;
    QContaPagarCTPCONTA: TStringField;
    QContaPagarCTPSITUACAO: TStringField;
    QContaPagarCTPOBSERVACAO: TStringField;
    QContaPagarCTPUSUARIO: TStringField;
    QContaPagarCTPCHEQUE: TStringField;
    QContaPagarCTPPORTADOR: TStringField;
    QContaPagarCTPBANCODEPTO: TStringField;
    QContaPagarCTPAGENCIA: TStringField;
    QContaPagarCTPCONTACORRENTE: TStringField;
    QContaPagarCTPLIBERADO: TStringField;
    CDSContaPagarCTPCOD: TIntegerField;
    CDSContaPagarCTPFORNECEDOR: TIntegerField;
    CDSContaPagarCTPTIPOCONTA: TStringField;
    CDSContaPagarCTPCADASTRO: TDateField;
    CDSContaPagarCTPEMISSAO: TDateField;
    CDSContaPagarCTPVENCIMENTO: TDateField;
    CDSContaPagarCTPLIQUIDACAO: TDateField;
    CDSContaPagarCTPDOCUMENTO: TIntegerField;
    CDSContaPagarCTPSERIE: TStringField;
    CDSContaPagarCTPBANCO: TIntegerField;
    CDSContaPagarCTPVALOR: TFloatField;
    CDSContaPagarCTPSALDO: TFloatField;
    CDSContaPagarCTPJURO: TFloatField;
    CDSContaPagarCTPMULTA: TFloatField;
    CDSContaPagarCTPCONTA: TStringField;
    CDSContaPagarCTPSITUACAO: TStringField;
    CDSContaPagarCTPOBSERVACAO: TStringField;
    CDSContaPagarCTPUSUARIO: TStringField;
    CDSContaPagarCTPCHEQUE: TStringField;
    CDSContaPagarCTPPORTADOR: TStringField;
    CDSContaPagarCTPBANCODEPTO: TStringField;
    CDSContaPagarCTPAGENCIA: TStringField;
    CDSContaPagarCTPCONTACORRENTE: TStringField;
    CDSContaPagarCTPLIBERADO: TStringField;
    CDSContaPagarFornecedor: TStringField;
    CDSContaPagarBanco: TStringField;
    CDSContaPagarConta: TStringField;
    QInstitutoINSTIPOSISTEMA: TStringField;
    CDSInstitutoINSTIPOSISTEMA: TStringField;
    QAlunoLkpALUCOD: TIntegerField;
    QAlunoLkpALUNOME: TStringField;
    QAlunoLkpALUENDERECO: TStringField;
    QAlunoLkpALUBAIRRO: TStringField;
    QAlunoLkpALUCIDADE: TIntegerField;
    QAlunoLkpALUCEP: TStringField;
    QAlunoLkpALUFONE: TStringField;
    QAlunoLkpALUFAX: TStringField;
    QAlunoLkpALUCELULAR: TStringField;
    QAlunoLkpALUEMAIL: TStringField;
    QAlunoLkpALUCPF: TStringField;
    QAlunoLkpALUIDENTIDADE: TStringField;
    QAlunoLkpALUCARTEIRA: TStringField;
    QAlunoLkpALUNACIONALIDADE: TStringField;
    QAlunoLkpALUNASCIMENTO: TDateField;
    QAlunoLkpALUNATURALIDADE: TIntegerField;
    QAlunoLkpALUSITUACAO: TStringField;
    QAlunoLkpALUESTADOCIVIL: TStringField;
    QAlunoLkpALUORGAOEXPEDIDOR: TStringField;
    QAlunoLkpALUDATAEXPEDICAO: TDateField;
    QAlunoLkpALUSEXO: TStringField;
    QAlunoLkpALUNOMEMAE: TStringField;
    QAlunoLkpALUNOMEPAI: TStringField;
    QAlunoLkpALUMIDIA: TStringField;
    QAlunoLkpALUCURSO: TIntegerField;
    QAlunoLkpALUORIENTADOR: TIntegerField;
    QAlunoLkpALUCARTEIRINHA: TStringField;
    QAlunoLkpALUCRACHA: TStringField;
    QAlunoLkpALUCERTIFICADO: TStringField;
    QAlunoLkpALUINDICACAO: TStringField;
    QAlunoLkpALUINDICACAOVALOR: TFloatField;
    QAlunoLkpALUINDICACAOPAGO: TStringField;
    QAlunoLkpALUCURSOINICIO: TDateField;
    QAlunoLkpALUCURSOFIM: TDateField;
    QAlunoLkpALUMONOTITULO: TStringField;
    QAlunoLkpALUMONODATA: TDateField;
    QAlunoLkpALUMONONOTA: TFloatField;
    QAlunoLkpALUBLOQ: TStringField;
    QAlunoLkpALUBLOQDATA: TDateField;
    QAlunoLkpALUSENHA: TStringField;
    QAlunoLkpALUENTREGOUDIPLOMA: TStringField;
    QAlunoLkpALUENTREGOUCPF: TStringField;
    QAlunoLkpALUENTREGOURG: TStringField;
    QAlunoLkpALUBOLSA: TIntegerField;
    QAlunoLkpALUEMAILALT: TStringField;
    QAlunoLkpALURESPONSAVEL: TStringField;
    QAlunoLkpALURESPONSAVELCPF: TStringField;
    QAlunoLkpALUALTERAR: TStringField;
    QAlunoLkpCIDNOME: TStringField;
    QAlunoLkpCIDUF: TStringField;
    QAlunoLkpCURNOME: TStringField;
    QAlunoLkpCURTURMA: TStringField;
    CDSAlunoLkpALUCOD: TIntegerField;
    CDSAlunoLkpALUNOME: TStringField;
    CDSAlunoLkpALUENDERECO: TStringField;
    CDSAlunoLkpALUBAIRRO: TStringField;
    CDSAlunoLkpALUCIDADE: TIntegerField;
    CDSAlunoLkpALUCEP: TStringField;
    CDSAlunoLkpALUFONE: TStringField;
    CDSAlunoLkpALUFAX: TStringField;
    CDSAlunoLkpALUCELULAR: TStringField;
    CDSAlunoLkpALUEMAIL: TStringField;
    CDSAlunoLkpALUCPF: TStringField;
    CDSAlunoLkpALUIDENTIDADE: TStringField;
    CDSAlunoLkpALUCARTEIRA: TStringField;
    CDSAlunoLkpALUNACIONALIDADE: TStringField;
    CDSAlunoLkpALUNASCIMENTO: TDateField;
    CDSAlunoLkpALUNATURALIDADE: TIntegerField;
    CDSAlunoLkpALUSITUACAO: TStringField;
    CDSAlunoLkpALUESTADOCIVIL: TStringField;
    CDSAlunoLkpALUORGAOEXPEDIDOR: TStringField;
    CDSAlunoLkpALUDATAEXPEDICAO: TDateField;
    CDSAlunoLkpALUSEXO: TStringField;
    CDSAlunoLkpALUNOMEMAE: TStringField;
    CDSAlunoLkpALUNOMEPAI: TStringField;
    CDSAlunoLkpALUMIDIA: TStringField;
    CDSAlunoLkpALUCURSO: TIntegerField;
    CDSAlunoLkpALUORIENTADOR: TIntegerField;
    CDSAlunoLkpALUCARTEIRINHA: TStringField;
    CDSAlunoLkpALUCRACHA: TStringField;
    CDSAlunoLkpALUCERTIFICADO: TStringField;
    CDSAlunoLkpALUINDICACAO: TStringField;
    CDSAlunoLkpALUINDICACAOVALOR: TFloatField;
    CDSAlunoLkpALUINDICACAOPAGO: TStringField;
    CDSAlunoLkpALUCURSOINICIO: TDateField;
    CDSAlunoLkpALUCURSOFIM: TDateField;
    CDSAlunoLkpALUMONOTITULO: TStringField;
    CDSAlunoLkpALUMONODATA: TDateField;
    CDSAlunoLkpALUMONONOTA: TFloatField;
    CDSAlunoLkpALUBLOQ: TStringField;
    CDSAlunoLkpALUBLOQDATA: TDateField;
    CDSAlunoLkpALUSENHA: TStringField;
    CDSAlunoLkpALUENTREGOUDIPLOMA: TStringField;
    CDSAlunoLkpALUENTREGOUCPF: TStringField;
    CDSAlunoLkpALUENTREGOURG: TStringField;
    CDSAlunoLkpALUBOLSA: TIntegerField;
    CDSAlunoLkpALUEMAILALT: TStringField;
    CDSAlunoLkpALURESPONSAVEL: TStringField;
    CDSAlunoLkpALURESPONSAVELCPF: TStringField;
    CDSAlunoLkpALUALTERAR: TStringField;
    CDSAlunoLkpCIDNOME: TStringField;
    CDSAlunoLkpCIDUF: TStringField;
    CDSAlunoLkpCURNOME: TStringField;
    CDSAlunoLkpCURTURMA: TStringField;
    QAlunoLkpNATUCIDADE: TStringField;
    QAlunoLkpNATUUF: TStringField;
    CDSAlunoLkpNATUCIDADE: TStringField;
    CDSAlunoLkpNATUUF: TStringField;
    QPlanoContaPLASA: TStringField;
    QPlanoContaPLADC: TStringField;
    CDSPlanoContaPLASA: TStringField;
    CDSPlanoContaPLADC: TStringField;
    QFormaPgtoFORCONTAVALORDEBITOCTP: TStringField;
    QFormaPgtoFORCONTAVALORCREDITOCTP: TStringField;
    QFormaPgtoFORCONTADESCONTODEBITOCTP: TStringField;
    QFormaPgtoFORCONTADESCONTOCREDITOCTP: TStringField;
    QFormaPgtoFORCONTAJUROCREDITOCTP: TStringField;
    QFormaPgtoFORCONTAJURODEBITOCTP: TStringField;
    QFormaPgtoFORHISTPADRAOVALORCTP: TIntegerField;
    QFormaPgtoFORHISTPADRAODESCONTOCTP: TIntegerField;
    QFormaPgtoFORHISTPADRAOJUROCTP: TIntegerField;
    CDSFormaPgtoFORCONTAVALORDEBITOCTP: TStringField;
    CDSFormaPgtoFORCONTAVALORCREDITOCTP: TStringField;
    CDSFormaPgtoFORCONTADESCONTODEBITOCTP: TStringField;
    CDSFormaPgtoFORCONTADESCONTOCREDITOCTP: TStringField;
    CDSFormaPgtoFORCONTAJUROCREDITOCTP: TStringField;
    CDSFormaPgtoFORCONTAJURODEBITOCTP: TStringField;
    CDSFormaPgtoFORHISTPADRAOVALORCTP: TIntegerField;
    CDSFormaPgtoFORHISTPADRAODESCONTOCTP: TIntegerField;
    CDSFormaPgtoFORHISTPADRAOJUROCTP: TIntegerField;
    CDSFormaPgtoValorDebitoCTP: TStringField;
    CDSFormaPgtoValorCreditoCTP: TStringField;
    CDSFormaPgtoDescontoDebitoCTP: TStringField;
    CDSFormaPgtoDescontoCreditoCTP: TStringField;
    CDSFormaPgtoJuroDebitoCTP: TStringField;
    CDSFormaPgtoJuroCreditoCTP: TStringField;
    CDSFormaPgtoHistValorCTP: TStringField;
    CDSFormaPgtoHistDescontoCTP: TStringField;
    CDSFormaPgtoHistJuroCTP: TStringField;
    QLctoContabilLCTCOMPLEMENTO: TMemoField;
    CDSLctoContabilLCTCOMPLEMENTO: TMemoField;
    QInstitutoINSCAB: TBlobField;
    QInstitutoINSFIGURA: TBlobField;
    QInstitutoINSFIGURAALT: TBlobField;
    CDSInstitutoINSCAB: TBlobField;
    CDSInstitutoINSFIGURA: TBlobField;
    CDSInstitutoINSFIGURAALT: TBlobField;
    QNetworkingNETDESCONTO: TFloatField;
    QNetworkingNETLOGO: TBlobField;
    CDSNetworkingNETDESCONTO: TFloatField;
    CDSNetworkingNETLOGO: TBlobField;
    QAviso: TSQLQuery;
    CDSAviso: TClientDataSet;
    DSPAviso: TDataSetProvider;
    DSAviso: TDataSource;
    QAvisoAVICOD: TIntegerField;
    QAvisoAVIDATA: TDateField;
    QAvisoAVIUSUARIO: TStringField;
    QAvisoAVIARQUIVO: TStringField;
    CDSAvisoAVICOD: TIntegerField;
    CDSAvisoAVIDATA: TDateField;
    CDSAvisoAVIUSUARIO: TStringField;
    CDSAvisoAVIARQUIVO: TStringField;
    QAvisoAVIMENSAGEM: TMemoField;
    CDSAvisoAVIMENSAGEM: TMemoField;
    QAvisoAVITIPO: TStringField;
    CDSAvisoAVITIPO: TStringField;
    QAvisoAVIARQUIVO1: TStringField;
    QAvisoAVIARQUIVO2: TStringField;
    QAvisoAVIARQUIVO3: TStringField;
    CDSAvisoAVIARQUIVO1: TStringField;
    CDSAvisoAVIARQUIVO2: TStringField;
    CDSAvisoAVIARQUIVO3: TStringField;
    CDSAlunoDisciplinaSomaHa: TAggregateField;
    QAvisoCurso: TSQLQuery;
    CDSAvisoCurso: TClientDataSet;
    DSPAvisoCurso: TDataSetProvider;
    DSAvisoCurso: TDataSource;
    QAvisoCursoAVICURAVISO: TIntegerField;
    QAvisoCursoAVICURCURSO: TIntegerField;
    CDSAvisoCursoAVICURAVISO: TIntegerField;
    CDSAvisoCursoAVICURCURSO: TIntegerField;
    CDSAvisoCursocurso: TStringField;
    QAvisoAVILINHAS: TIntegerField;
    CDSAvisoAVILINHAS: TIntegerField;
    QAlunoALUCERTSOLICITADO: TDateField;
    QAlunoALUCERTENTREGA: TDateField;
    CDSAlunoALUCERTSOLICITADO: TDateField;
    CDSAlunoALUCERTENTREGA: TDateField;
    QAlunoALURESPPGTO: TIntegerField;
    CDSAlunoALURESPPGTO: TIntegerField;
    QContaPagarCTPFORMAPGTO: TIntegerField;
    QContaPagarCTPLCTOCONTABILVALOR: TIntegerField;
    QContaPagarCTPLCTOCONTABILDESCONTO: TIntegerField;
    QContaPagarCTPLCTOCONTABILJUROS: TIntegerField;
    CDSContaPagarCTPLCTOCONTABILJUROS: TIntegerField;
    CDSContaPagarCTPLCTOCONTABILDESCONTO: TIntegerField;
    CDSContaPagarCTPLCTOCONTABILVALOR: TIntegerField;
    CDSContaPagarCTPFORMAPGTO: TIntegerField;
    CDSContaPagarFormaPgto: TStringField;
    CDSGrupoCurso: TClientDataSet;
    DSPGrupoCurso: TDataSetProvider;
    QGrupoCurso: TSQLQuery;
    DSGrupoCurso: TDataSource;
    QGrupoCursoGRUCOD: TIntegerField;
    QGrupoCursoGRUNOME: TStringField;
    CDSGrupoCursoGRUCOD: TIntegerField;
    CDSGrupoCursoGRUNOME: TStringField;
    QCursoCURGRUPO: TIntegerField;
    CDSCursoCURGRUPO: TIntegerField;
    QInstitutoINSCABINF: TBlobField;
    CDSInstitutoINSCABINF: TBlobField;
    SaveDialogDoc: TSaveDialog;
    PMGrid: TPopupMenu;
    MITamanhoColunas: TMenuItem;
    N1: TMenuItem;
    MIGravarConfiguracao: TMenuItem;
    MICarregarConfiguracao: TMenuItem;
    ColorDialog: TColorDialog;
    FontDialog: TFontDialog;
    ConfigurarFonte1: TMenuItem;
    QCursoCURTIPO: TStringField;
    CDSCursoCURTIPO: TStringField;
    QAlunoDisciplinaALUDISSITUACAO: TStringField;
    QAlunoDisciplinaALUDISNOTA1: TFloatField;
    QAlunoDisciplinaALUDISNOTA2: TFloatField;
    QAlunoDisciplinaALUDISNOTA3: TFloatField;
    QAlunoDisciplinaALUDISNOTA4: TFloatField;
    QAlunoDisciplinaALUDISFREQUENCIA1: TFloatField;
    QAlunoDisciplinaALUDISFREQUENCIA2: TFloatField;
    QAlunoDisciplinaALUDISFREQUENCIA3: TFloatField;
    QAlunoDisciplinaALUDISFREQUENCIA4: TFloatField;
    CDSAlunoDisciplinaALUDISSITUACAO: TStringField;
    CDSAlunoDisciplinaALUDISNOTA1: TFloatField;
    CDSAlunoDisciplinaALUDISNOTA2: TFloatField;
    CDSAlunoDisciplinaALUDISNOTA3: TFloatField;
    CDSAlunoDisciplinaALUDISNOTA4: TFloatField;
    CDSAlunoDisciplinaALUDISFREQUENCIA1: TFloatField;
    CDSAlunoDisciplinaALUDISFREQUENCIA2: TFloatField;
    CDSAlunoDisciplinaALUDISFREQUENCIA3: TFloatField;
    CDSAlunoDisciplinaALUDISFREQUENCIA4: TFloatField;
    QAlunoLancALUDISSITUACAO: TStringField;
    QAlunoLancALUDISNOTA1: TFloatField;
    QAlunoLancALUDISNOTA2: TFloatField;
    QAlunoLancALUDISNOTA3: TFloatField;
    QAlunoLancALUDISNOTA4: TFloatField;
    QAlunoLancALUDISFREQUENCIA1: TFloatField;
    QAlunoLancALUDISFREQUENCIA2: TFloatField;
    QAlunoLancALUDISFREQUENCIA3: TFloatField;
    QAlunoLancALUDISFREQUENCIA4: TFloatField;
    CDSAlunoLancALUDISSITUACAO: TStringField;
    CDSAlunoLancALUDISNOTA1: TFloatField;
    CDSAlunoLancALUDISNOTA2: TFloatField;
    CDSAlunoLancALUDISNOTA3: TFloatField;
    CDSAlunoLancALUDISNOTA4: TFloatField;
    CDSAlunoLancALUDISFREQUENCIA1: TFloatField;
    CDSAlunoLancALUDISFREQUENCIA2: TFloatField;
    CDSAlunoLancALUDISFREQUENCIA3: TFloatField;
    CDSAlunoLancALUDISFREQUENCIA4: TFloatField;
    QUsuarioUSUPROFESSOR: TIntegerField;
    CDSUsuarioUSUPROFESSOR: TIntegerField;
    QLctoContabilCOMCOMPLEMENTO: TStringField;
    CDSLctoContabilCOMCOMPLEMENTO: TStringField;
    QUsuarioPRONOME: TStringField;
    QUsuarioNATURALIDADE: TStringField;
    QUsuarioCIDADE: TStringField;
    CDSUsuarioPRONOME: TStringField;
    CDSUsuarioNATURALIDADE: TStringField;
    CDSUsuarioCIDADE: TStringField;
    DSQUsuario: TDataSource;
    QItemUsuarioPRONOME: TStringField;
    CDSUsuarioQItemUsuario: TDataSetField;
    CDSItemUsuarioPRONOME: TStringField;
    QParamEmpCIDNOME: TStringField;
    CDSParamEmpCIDNOME: TStringField;
    DSQAluno: TDataSource;
    DSQAlunoDisciplina: TDataSource;
    QAlunoALUPESQUISA: TStringField;
    QAlunoCIDADE: TStringField;
    QAlunoUF: TStringField;
    QAlunoPRONOME: TStringField;
    QAlunoNETNOME: TStringField;
    CDSAlunoCURNOME: TStringField;
    CDSAlunoCURTURMA: TStringField;
    CDSAlunoALUPESQUISA: TStringField;
    CDSAlunoCIDADE: TStringField;
    CDSAlunoUF: TStringField;
    CDSAlunoPRONOME: TStringField;
    CDSAlunoNETNOME: TStringField;
    QAlunoALUFOTO: TBlobField;
    CDSAlunoALUFOTO: TBlobField;
    QAlunoDisciplinaDISNOME: TStringField;
    CDSAlunoQAlunoDisciplina: TDataSetField;
    CDSAlunoQAlunoMensalidade: TDataSetField;
    CDSAlunoQAlunoServicoFin: TDataSetField;
    CDSAlunoDisciplinaQAlunoDisciplinaData: TDataSetField;
    QAlunoNATURALIDADE: TStringField;
    CDSAlunoNATURALIDADE: TStringField;
    CDSAlunoDisciplinaDISNOME: TStringField;
    DSQProfessor: TDataSource;
    QProfessorCIDNOME: TStringField;
    QProfessorGRUPRONOME: TStringField;
    CDSProfessorGRUPRONOME: TStringField;
    QProfessorDisciplinaDISNOME: TStringField;
    CDSProfessorDisciplinaDISNOME: TStringField;
    QProfessorGrupoGRUPRONOME: TStringField;
    CDSProfessorGrupoGRUPRONOME: TStringField;
    CDSProfessorCIDNOME: TStringField;
    DSQCurso: TDataSource;
    QCursoDisciplinaDISNOME: TStringField;
    QCursoDisciplinaPRONOME: TStringField;
    DSQCursoDisciplina: TDataSource;
    DSQMaterial: TDataSource;
    CDSMaterialQMaterialAutor: TDataSetField;
    CDSMaterialQMaterialAssunto: TDataSetField;
    DSQDre: TDataSource;
    DSQDreItem: TDataSource;
    CDSDreQDreItem: TDataSetField;
    CDSCursoQCursoDisciplina: TDataSetField;
    QCursoPLANEGNOME: TStringField;
    QCursoPRONOME: TStringField;
    QCursoGRUNOME: TStringField;
    CDSCursoPLANEGNOME: TStringField;
    CDSCursoPRONOME: TStringField;
    CDSCursoGRUNOME: TStringField;
    QCursoDisciplinaPRORESUMOTITULACAO: TStringField;
    CDSCursoDisciplinaDISNOME: TStringField;
    CDSCursoDisciplinaPRONOME: TStringField;
    CDSCursoDisciplinaPRORESUMOTITULACAO: TStringField;
    QAlunoLkpALUDESCONTO: TSingleField;
    CDSAlunoLkpALUDESCONTO: TSingleField;
    QAlunoALUDESCONTO: TSingleField;
    CDSAlunoALUDESCONTO: TSingleField;
    QMensalidadeFORNOME: TStringField;
    QMensalidadePRONOME: TStringField;
    QMensalidadeDISNOME: TStringField;
    CDSMensalidadeFORNOME: TStringField;
    CDSMensalidadePRONOME: TStringField;
    CDSMensalidadeDISNOME: TStringField;
    QTela: TSQLQuery;
    CDSTela: TClientDataSet;
    DSPTela: TDataSetProvider;
    DSTela: TDataSource;
    QTelaTELUSUARIO: TStringField;
    QTelaTELTELA: TStringField;
    QTelaTELALTURA: TIntegerField;
    QTelaTELLARGURA: TIntegerField;
    CDSTelaTELUSUARIO: TStringField;
    CDSTelaTELTELA: TStringField;
    CDSTelaTELALTURA: TIntegerField;
    CDSTelaTELLARGURA: TIntegerField;
    QDbGrid: TSQLQuery;
    CDSDbGrid: TClientDataSet;
    DSPDbGrid: TDataSetProvider;
    DSDbGrid: TDataSource;
    QDbGridGRIDUSUARIO: TStringField;
    QDbGridGRIDTELA: TStringField;
    QDbGridGRIDNOME: TStringField;
    QDbGridGRIDPOSICAO: TIntegerField;
    QDbGridGRIDALINHAMENTO: TStringField;
    QDbGridGRIDCAMPO: TStringField;
    QDbGridGRIDTITULO: TStringField;
    QDbGridGRIDTAMANHO: TIntegerField;
    QDbGridGRIDVISIVEL: TStringField;
    CDSDbGridGRIDUSUARIO: TStringField;
    CDSDbGridGRIDTELA: TStringField;
    CDSDbGridGRIDNOME: TStringField;
    CDSDbGridGRIDPOSICAO: TIntegerField;
    CDSDbGridGRIDALINHAMENTO: TStringField;
    CDSDbGridGRIDCAMPO: TStringField;
    CDSDbGridGRIDTITULO: TStringField;
    CDSDbGridGRIDTAMANHO: TIntegerField;
    CDSDbGridGRIDVISIVEL: TStringField;
    ImageListMenu: TImageList;
    BalloonHint1: TBalloonHint;
    QCursoCURHORARIOFIM: TStringField;
    CDSCursoCURHORARIOFIM: TStringField;
    QAlunoALURESPRG: TStringField;
    QAlunoALURESPNOMEMAE: TStringField;
    QAlunoALURESPNASC: TDateField;
    CDSAlunoALURESPRG: TStringField;
    CDSAlunoALURESPNOMEMAE: TStringField;
    CDSAlunoALURESPNASC: TDateField;
    QAlunoALURESPEND: TStringField;
    QAlunoALURESPBAIRRO: TStringField;
    QAlunoALURESPFONE: TStringField;
    QAlunoALURESPCEP: TStringField;
    QAlunoALURESPCID: TIntegerField;
    CDSAlunoALURESPEND: TStringField;
    CDSAlunoALURESPBAIRRO: TStringField;
    CDSAlunoALURESPFONE: TStringField;
    CDSAlunoALURESPCEP: TStringField;
    CDSAlunoALURESPCID: TIntegerField;
    QAlunoRESPCID: TStringField;
    CDSAlunoRESPCID: TStringField;
          procedure CDSParamEmpAfterInsert(DataSet: TDataSet);
          procedure CDSProgramaAfterInsert(DataSet: TDataSet);
          procedure CDSCidadeAfterInsert(DataSet: TDataSet);
          procedure CDSAlunoAfterInsert(DataSet: TDataSet);
          procedure CDSProfessorAfterInsert(DataSet: TDataSet);
          procedure CDSCursoAfterInsert(DataSet: TDataSet);
          procedure CDSBancoAfterInsert(DataSet: TDataSet);
          procedure CDSDisciplinaAfterInsert(DataSet: TDataSet);
          procedure CDSGrupoProAfterInsert(DataSet: TDataSet);
          procedure CDSHistPadraoAfterInsert(DataSet: TDataSet);
          procedure CDSPlanoNegociosAfterInsert(DataSet: TDataSet);
          procedure CDSLctoContabilAfterInsert(DataSet: TDataSet);
          procedure CDSCursoCalcFields(DataSet: TDataSet);
          procedure CDSMensalidadeCalcFields(DataSet: TDataSet);
          procedure CDSAlunoLancAfterPost(DataSet: TDataSet);
          procedure CDSFormaPgtoAfterInsert(DataSet: TDataSet);
          procedure CDSAlunoDisciplinaDataAfterInsert(DataSet: TDataSet);
          procedure CDSCursoDisciplinaDataAfterInsert(DataSet: TDataSet);
          procedure CDSMensalidadeBeforePost(DataSet: TDataSet);
          procedure CDSDreAfterInsert(DataSet: TDataSet);
          procedure CDSMensalidadeAfterPost(DataSet: TDataSet);
          procedure CDSLctoContabilAfterPost(DataSet: TDataSet);
          procedure CDSAlunoLancBeforePost(DataSet: TDataSet);
          procedure CDSAlunoDisciplinaBeforePost(DataSet: TDataSet);
          procedure CDSNetworkingAfterInsert(DataSet: TDataSet);
          procedure CDSOrcamentoAfterInsert(DataSet: TDataSet);
          procedure CDSServicosFinAfterInsert(DataSet: TDataSet);
          procedure DataModuleCreate(Sender: TObject);
          procedure CDSIdentificadorAfterInsert(DataSet: TDataSet);
          procedure CDSAutorAfterInsert(DataSet: TDataSet);
          procedure CDSEditoraAfterInsert(DataSet: TDataSet);
    procedure CDSAssuntoAfterInsert(DataSet: TDataSet);
    procedure CDSTipoMaterialAfterInsert(DataSet: TDataSet);
    procedure CDSAlunoFotoAfterInsert(DataSet: TDataSet);
    procedure CDSMaterialAfterInsert(DataSet: TDataSet);
    procedure CDSTransitoAfterInsert(DataSet: TDataSet);
    procedure CDSContaPagarAfterInsert(DataSet: TDataSet);
    procedure CDSAvisoAfterInsert(DataSet: TDataSet);
    procedure CDSCursoDisciplinaDataBeforePost(DataSet: TDataSet);
    procedure CDSAvisoAfterScroll(DataSet: TDataSet);
    procedure CDSAvisoCursoNewRecord(DataSet: TDataSet);
    procedure CDSGrupoCursoAfterInsert(DataSet: TDataSet);
    procedure RLPreviewSetup1Send(Sender: TObject);
    procedure MITamanhoColunasClick(Sender: TObject);
    procedure MIGravarConfiguracaoClick(Sender: TObject);
    procedure MICarregarConfiguracaoClick(Sender: TObject);
    procedure ConfigurarFonte1Click(Sender: TObject);
    procedure CDSAlunoDisciplinaALUDISNOTA1Change(Sender: TField);
    procedure CDSAlunoLancALUDISNOTA1Change(Sender: TField);
    procedure CDSAlunoDisciplinaAfterEdit(DataSet: TDataSet);
    procedure CDSAlunoLancAfterEdit(DataSet: TDataSet);
    procedure CDSLctoContabilReconcileError(DataSet: TCustomClientDataSet;
      E: EReconcileError; UpdateKind: TUpdateKind;
      var Action: TReconcileAction);
    procedure CDSCidadeReconcileError(DataSet: TCustomClientDataSet;
      E: EReconcileError; UpdateKind: TUpdateKind;
      var Action: TReconcileAction);
    procedure DSPAlunoBeforeUpdateRecord(Sender: TObject; SourceDS: TDataSet;
      DeltaDS: TCustomClientDataSet; UpdateKind: TUpdateKind;
      var Applied: Boolean);
    procedure DSPProfessorBeforeUpdateRecord(Sender: TObject;
      SourceDS: TDataSet; DeltaDS: TCustomClientDataSet;
      UpdateKind: TUpdateKind; var Applied: Boolean);
    procedure DSPCursoBeforeUpdateRecord(Sender: TObject; SourceDS: TDataSet;
      DeltaDS: TCustomClientDataSet; UpdateKind: TUpdateKind;
      var Applied: Boolean);
     private
          { Private declarations }
     public
          { Public declarations }
     end;

var
     DM: TDM;
     TipoSistema, Ssql, lUsuario: string;
     local : boolean = true;
     gDBGrid : TDBGrid;

implementation

uses UMenu, SendMailOptions, UFuncoes, UReconcileError, UAviso;

{$R *.dfm}

procedure TDm.CDSParamEmpAfterInsert(DataSet: TDataSet);
begin
     cdsparamempempcod.asinteger := max('EMPCOD', 'TPARAMEMP');
end;

procedure TDm.CDSProgramaAfterInsert(DataSet: TDataSet);
begin
     cdsprogramaprocod.asinteger := MAX('PROCOD', 'TPROGRAMA');
end;

procedure TDm.CDSCidadeAfterInsert(DataSet: TDataSet);
begin
     cdscidadecidcod.asinteger := MAX('CIDCOD', 'TCIDADE');
end;

procedure TDm.CDSCidadeReconcileError(DataSet: TCustomClientDataSet;
  E: EReconcileError; UpdateKind: TUpdateKind; var Action: TReconcileAction);
begin
     Action := HandleReconcileError(DataSet, UpdateKind, E);
end;

procedure TDm.CDSAlunoAfterInsert(DataSet: TDataSet);
begin
     CDSAlunoALUCOD.asinteger := MAX('ALUCOD', 'TALUNO');
     CDSAlunoALUNACIONALIDADE.asstring := 'Brasileira';
     CDSAlunoALUCERTIFICADO.asstring := 'N';
     CDSAlunoALUCARTEIRINHA.asstring := 'N';
     CDSAlunoALUCRACHA.asstring := 'N';
end;

procedure TDm.CDSProfessorAfterInsert(DataSet: TDataSet);
begin
     CDSProfessorPROCOD.asinteger := MAX('PROCOD', 'TPROFESSOR');
end;

procedure TDm.CDSCursoAfterInsert(DataSet: TDataSet);
begin
     CDSCursoCURCOD.asinteger := MAX('CURCOD', 'TCURSO');
end;

procedure TDm.CDSBancoAfterInsert(DataSet: TDataSet);
begin
     CDSBancoBANCOD.asinteger := MAX('BANCOD', 'TBANCO');
end;

procedure TDm.CDSDisciplinaAfterInsert(DataSet: TDataSet);
begin
     CDSDisciplinaDISCOD.asinteger := MAX('DISCOD', 'TDISCIPLINA');
end;

procedure TDm.CDSGrupoProAfterInsert(DataSet: TDataSet);
begin
     CDSGrupoProGRUPROCOD.asinteger := MAX('GRUPROCOD', 'TGRUPOPRO');
end;

procedure TDm.CDSHistPadraoAfterInsert(DataSet: TDataSet);
begin
     CDSHistPadraoHISCOD.asinteger := MAX('HISCOD', 'THISTPADRAO');
end;

procedure TDm.CDSPlanoNegociosAfterInsert(DataSet: TDataSet);
begin
     CDSPlanoNegociosPLANEGCOD.asinteger := MAX('PLANEGCOD', 'TPLANONEGOCIOS');
end;

procedure TDm.CDSLctoContabilAfterInsert(DataSet: TDataSet);
begin
     CDSLctoContabilLCTNUMERO.asinteger := MAX('LCTNUMERO', 'TLCTOCONTABIL');
end;

procedure TDm.CDSCursoCalcFields(DataSet: TDataSet);
begin
     CDSCursoliquido.asfloat := CDSCursoCURVALOR.asfloat - CDSCursoCURDESCONTO.asfloat;
end;

procedure TDm.CDSMensalidadeCalcFields(DataSet: TDataSet);
begin
     CDSMensalidadeliquido.asfloat := CDSMensalidadeMENVALOR.asfloat + CDSMensalidadeMENACRESCIMO.asfloat - CDSMensalidadeMENDESCONTO.asfloat - CDSMensalidadeMENBOLSA.asfloat;
end;

procedure TDm.CDSAlunoLancAfterPost(DataSet: TDataSet);
begin
     dm.CDSAlunoLanc.ApplyUpdates(0);
end;

procedure TDm.CDSFormaPgtoAfterInsert(DataSet: TDataSet);
begin
     CDSFormaPgtoFORCOD.asinteger := MAX('FORCOD', 'TFORMAPGTO');
end;

procedure TDm.CDSAlunoDisciplinaDataAfterInsert(DataSet: TDataSet);
begin
     dm.CDSAlunoDisciplinaDataALUDISDATAALUNO.asinteger := dm.CDSAlunoDisciplinaALUDISALUNO.asinteger;
     dm.CDSAlunoDisciplinaDataALUDISDATADISCIPLINA.asinteger := dm.CDSAlunoDisciplinaALUDISDISCIPLINA.asinteger;
     dm.CDSAlunoDisciplinaDataALUDISDATAPROFESSOR.asinteger := dm.CDSAlunoDisciplinaALUDISPROFESSOR.asinteger;
end;

procedure TDm.CDSCursoDisciplinaDataAfterInsert(DataSet: TDataSet);
begin
     dm.CDSCursoDisciplinaDataCurDISDATACurso.asinteger := dm.CDSCursoDisciplinaCurDISCurso.asinteger;
     dm.CDSCursoDisciplinaDataCurDISDATADISCIPLINA.asinteger := dm.CDSCursoDisciplinaCurDISDISCIPLINA.asinteger;
     dm.CDSCursoDisciplinaDataCurDISDATAPROFESSOR.asinteger := dm.CDSCursoDisciplinaCurDISPROFESSOR.asinteger;
end;

procedure TDm.CDSMensalidadeBeforePost(DataSet: TDataSet);
begin
     dm.CDSMensalidadeMENLIQUIDO.asfloat := dm.CDSMensalidadeliquido.asfloat;
end;

procedure TDm.CDSDreAfterInsert(DataSet: TDataSet);
begin
     CDSDreDRECOD.asinteger := MAX('DRECOD', 'TDRE');
end;

procedure TDm.CDSMensalidadeAfterPost(DataSet: TDataSet);
begin
     {if dm.CDSMensalidadeMENDATAPAGAMENTO.asdatetime < strtodate('01/01/2000') then
          showmessage('Atenção: Data menor que 01/01/2000, por favor verifique a data de pagamento!');}
end;

procedure TDm.CDSLctoContabilAfterPost(DataSet: TDataSet);
begin
     if dm.CDSLctoContabilLCTDATA.asdatetime < strtodate('01/01/2000') then
          showmessage('Atenção: Data menor que 01/01/2000, por favor verifique a data de pagamento da mensalidade ou a data do lançamento! Número: ' + dm.CDSLctoContabilLCTNUMERO.asstring);
end;

procedure TDm.CDSAlunoLancBeforePost(DataSet: TDataSet);
begin
     if valor_parametro(21) = '1' then
     begin
          if ((CDSAlunoLancALUDISNOTA.asfloat < 7) and (CDSAlunoLancALUDISNOTA.asfloat > 0)) or (CDSAlunoLancALUDISNOTA.asfloat > 10) then
          begin
               showmessage('Digite apenas notas maiores que 7 (sete) e menores que 10 (dez)!');
               Abort;
          end;
          if CDSAlunoLancALUDISFREQUENCIA.asfloat > 100 then
          begin
               showmessage('Digite apenas frequências menores que 100 (cem)!');
               Abort;
          end;
     end;
     if CDSAlunoLancALUDISDATA.IsNull then
          CDSAlunoLancALUDISDATA.AsDateTime := Date;
end;

procedure TDm.CDSAlunoDisciplinaBeforePost(DataSet: TDataSet);
begin
    if valor_parametro(21) = '1' then
    begin
         if ((dm.CDSAlunoDisciplinaALUDISNOTA.asfloat < 7) and (dm.CDSAlunoDisciplinaALUDISNOTA.asfloat > 0)) or (dm.CDSAlunoDisciplinaALUDISNOTA.asfloat > 10) then
         begin
              showmessage('Digite apenas notas maiores que 7(sete) e menores que 10 (dez)!');
              abort;
         end;
         if CDSAlunoLancALUDISFREQUENCIA.asfloat > 100 then
         begin
              showmessage('Digite apenas frequências menores que 100 (cem)!');
              Abort;
         end;
    end;
end;

procedure TDm.CDSNetworkingAfterInsert(DataSet: TDataSet);
begin
     CDSNetworkingNETCOD.asinteger := MAX('NETCOD', 'TNETWORKING');
end;

procedure TDm.CDSOrcamentoAfterInsert(DataSet: TDataSet);
begin
     CDSOrcamentoOrcNUMERO.asinteger := MAX('ORCNUMERO', 'TORCAMENTO');
end;

procedure TDm.CDSServicosFinAfterInsert(DataSet: TDataSet);
begin
     CDSServicosFinFINCOD.asinteger := MAX('FINCOD', 'TSERVICOSFIN');
end;

procedure TDm.DataModuleCreate(Sender: TObject);
var
    arq: TextFile;
    linha: string;
    i: integer;
begin
     if fileexists('c:\caminho.txt') then
     begin
          AssignFile(arq, 'C:\caminho.txt');
          Reset(arq);
          ReadLn(arq, linha);
          if uppercase(copy(linha, 1, 1)) <> 'C' then
          begin
               if FileExists(ExtractFilePath(Application.ExeName) + 'banco.fdb') then
               begin
                    if application.messagebox('Existe um banco de dados local, deseja acessa-lo? Caso contrário será acessado o banco de dados da rede', 'Atenção', mb_yesno + MB_ICONQUESTION) = mrno then
                    begin
                         sqlconnection.Params.Values['Database'] := linha;
                         local := false;
                    end;
               end
               else
                    sqlconnection.Params.Values['Database'] := linha;
          end
          else
               sqlconnection.Params.Values['Database'] := linha;
          closefile(arq);
     end;

     //Carregando(True);
     try
          SQLConnection.connected := true;
          Carregando(False);
     except
          on E: Exception do
          begin
               Carregando(False);
               showmessage('Impossível conectar com o banco de dados!' + #13 + #13 + E.Message);
               if fileexists('c:\caminho.txt') then
                    ShellExecute(GetDesktopWindow, 'open', pchar('c:\caminho.txt'), nil, nil, sw_ShowNormal);
               application.terminate;
          end;
     end;

     for i := 0 to DM.ComponentCount - 1 do
        if DM.Components[i] is TClientDataSet then
            TClientDataSet(DM.Components[i]).OnReconcileError := dm.CDSCidadeReconcileError;

     Carregando(True);
     atualizar_sistema;
     ThreadExecSql(dm.cdsusuario);
end;

procedure TDm.DSPAlunoBeforeUpdateRecord(Sender: TObject; SourceDS: TDataSet;
  DeltaDS: TCustomClientDataSet; UpdateKind: TUpdateKind; var Applied: Boolean);
begin
    if SourceDS = QAluno then
    begin
        DeltaDS.FieldByName('CIDADE').ProviderFlags := [pfHidden];
        DeltaDS.FieldByName('NATURALIDADE').ProviderFlags := [pfHidden];
        DeltaDS.FieldByName('CURTURMA').ProviderFlags := [pfHidden];
        DeltaDS.FieldByName('CURNOME').ProviderFlags := [pfHidden];
        DeltaDS.FieldByName('UF').ProviderFlags := [pfHidden];
        DeltaDS.FieldByName('PRONOME').ProviderFlags := [pfHidden];
        DeltaDS.FieldByName('NETNOME').ProviderFlags := [pfHidden];
    end;
end;

procedure TDm.DSPCursoBeforeUpdateRecord(Sender: TObject; SourceDS: TDataSet;
  DeltaDS: TCustomClientDataSet; UpdateKind: TUpdateKind; var Applied: Boolean);
begin
    if SourceDS = QCurso then
    begin
        DeltaDS.FieldByName('PRONOME').ProviderFlags := [pfHidden];
        DeltaDS.FieldByName('PLANEGNOME').ProviderFlags := [pfHidden];
        DeltaDS.FieldByName('GRUNOME').ProviderFlags := [pfHidden];
    end;
end;

procedure TDm.DSPProfessorBeforeUpdateRecord(Sender: TObject;
  SourceDS: TDataSet; DeltaDS: TCustomClientDataSet; UpdateKind: TUpdateKind;
  var Applied: Boolean);
begin
    if SourceDS = QProfessor then
    begin
        DeltaDS.FieldByName('CIDNOME').ProviderFlags := [pfHidden];
        DeltaDS.FieldByName('GRUPRONOME').ProviderFlags := [pfHidden];
    end;
end;

procedure TDm.CDSIdentificadorAfterInsert(DataSet: TDataSet);
begin
     CDSIdentificadorIDECOD.asinteger := MAX('IDECOD', 'TIDENTIFICADOR');
end;

procedure TDm.CDSAutorAfterInsert(DataSet: TDataSet);
begin
     CDSAutorAutCOD.asinteger := MAX('AUTCOD', 'TAUTOR');
end;

procedure TDm.CDSEditoraAfterInsert(DataSet: TDataSet);
begin
     CDSEditoraEdiCOD.asinteger := MAX('EDICOD', 'TEDITORA');
end;

procedure TDm.CDSAssuntoAfterInsert(DataSet: TDataSet);
begin
     CDSAssuntoAssCOD.asinteger := MAX('ASSCOD', 'TASSUNTO');
end;

procedure TDm.CDSTipoMaterialAfterInsert(DataSet: TDataSet);
begin
      CDSTipoMaterialTIPMATCOD.asinteger := MAX('TIPMATCOD', 'TTIPOMATERIAL');
end;

procedure TDm.CDSAlunoFotoAfterInsert(DataSet: TDataSet);
begin
     CDSAlunoFotoALUCOD.asinteger := CDSAlunoALUCOD.asinteger;
end;

procedure TDm.CDSMaterialAfterInsert(DataSet: TDataSet);
begin
     CDSMaterialMATCOD.asinteger := MAX('MATCOD', 'TMATERIAL');
     CDSMaterialMATSITUACAO.asString := 'Normal';
end;

procedure TDm.CDSTransitoAfterInsert(DataSet: TDataSet);
begin
     CDSTransitoTRACOD.asinteger := MAX('TRACOD', 'TTRANSITO');
end;

procedure TDm.CDSContaPagarAfterInsert(DataSet: TDataSet);
begin
     CDSContaPagarCTPCOD.asinteger := MAX('CTPCOD', 'TCONTAPAGAR');
end;

procedure TDm.CDSAvisoAfterInsert(DataSet: TDataSet);
begin
     CDSAvisoAVICOD.asinteger := MAX('AVICOD', 'TAVISO');
     CDSAvisoAVIDATA.AsDateTime := date;
     CDSAvisoAVITIPO.Asstring := 'A';     
end;

procedure TDm.CDSCursoDisciplinaDataBeforePost(DataSet: TDataSet);
begin
     if trim(CDSCursoDisciplinaDataCURDISDATADATA.asString) = '' then
     begin
          CDSCursoDisciplinaData.Cancel;
          abort;
     end;
end;

procedure TDm.CDSAvisoAfterScroll(DataSet: TDataSet);
begin
     CDSAvisoCurso.Close;
     QAvisoCurso.Params.ParamByName('AVICURAVISO').AsInteger := CDSAvisoAviCod.AsInteger; 
     CDSAvisoCurso.Open;
     if FAviso <> nil then
     begin
          FAviso.chkCurso.Items.Clear;
          if not CDSGrupoCurso.Active then
               CDSGrupoCurso.Open;
          //CDSGrupoCurso.AfterScroll := nil;
          CDSGrupoCurso.First;
          while not CDSGrupoCurso.Eof do
          begin
               FAviso.chkCurso.Items.Add(FormatFloat('0000',CDSGrupoCursoGRUCOD.asInteger) + '-' + CDSGrupoCursoGRUNOME.asString);
               if CDSAvisoCurso.locate('AVICURCURSO', CDSGrupoCursoGRUCOD.AsINteger, [loPartialKey, loCaseInsensitive]) then
                    FAviso.chkCurso.Checked[FAviso.chkCurso.Items.Count - 1] := True;
               CDSGrupoCurso.Next;
          end;
          //CDSGrupoCurso.AfterScroll := CDSGrupoCursoAfterScroll;
     end;
end;

procedure TDm.CDSAvisoCursoNewRecord(DataSet: TDataSet);
begin
     CDSAvisoCursoAVICURAVISO.AsInteger := CDSAvisoAVICOD.AsInteger;
end;

procedure TDm.CDSGrupoCursoAfterInsert(DataSet: TDataSet);
begin
     CDSGrupoCursoGruCod.asinteger := MAX('GRUCOD', 'TGRUPOCURSO');
end;

procedure TDm.RLPreviewSetup1Send(Sender: TObject);
begin
  TFormSendMailOptions.CreateShowAndFree(TRLPreviewForm(Sender).Preview.Pages);
end;

procedure TDm.MITamanhoColunasClick(Sender: TObject);
begin
    AutoFitColunasGrid(gDBGrid);
end;

procedure TDm.MIGravarConfiguracaoClick(Sender: TObject);
begin
    try
        gDBGrid.Columns.SaveToFile(ExtractFilePath(application.ExeName) + '\' + getForm(gDbGrid).Name);
    except
        On E : Exception do
            Showmessage('Erro ao salvar as configurações: ' + E.Message);
    end;
end;

procedure TDm.MICarregarConfiguracaoClick(Sender: TObject);
begin
    try
        if not directoryExists(ExtractFilePath(application.ExeName)) then
            ForceDirectories(ExtractFilePath(application.ExeName));

        if FileExists(ExtractFilePath(application.ExeName) + '\' + getForm(gDbGrid).Name) then
            gDBGrid.Columns.loadFromfile(ExtractFilePath(application.ExeName) + '\' + getForm(gDbGrid).Name);
    except
        On E : Exception do
            Showmessage('Erro ao carregar as configurações do grid: ' + E.Message);
    end;
end;

procedure TDm.ConfigurarFonte1Click(Sender: TObject);
var i : byte;
begin
    Dm.FontDialog.Font := gDBGrid.Columns[0].Font;
    if Dm.FontDialog.Execute then
        for i := 0 to gDBGrid.Columns.Count - 1 do
            gDBGrid.Columns[i].Font := Dm.FontDialog.Font;
end;

procedure TDm.CDSAlunoDisciplinaALUDISNOTA1Change(Sender: TField);
begin
    if CDSAlunoDisciplina.State in [dsEdit, dsInsert] then
    begin
        CDSAlunoDisciplinaALUDISFREQUENCIA.AsFloat :=
             Arredonda( (CDSAlunoDisciplinaALUDISFREQUENCIA1.AsFloat + CDSAlunoDisciplinaALUDISFREQUENCIA2.AsFloat + CDSAlunoDisciplinaALUDISFREQUENCIA3.AsFloat) / 3, 2);

        CDSAlunoDisciplinaALUDISNOTA.AsFloat :=
             Arredonda( (CDSAlunoDisciplinaALUDISNOTA1.AsFloat + CDSAlunoDisciplinaALUDISNOTA2.AsFloat + CDSAlunoDisciplinaALUDISNOTA3.AsFloat) / 3, 2);
            //CDSAlunoDisciplinaALUDISNOTA4.AsFloat;
    end;
end;

procedure TDm.CDSAlunoLancALUDISNOTA1Change(Sender: TField);
begin
    if CDSAlunoLanc.State in [dsEdit, dsInsert] then
    begin
        CDSAlunoLancALUDISFREQUENCIA.AsFloat :=
             Arredonda( (CDSAlunoLancALUDISFREQUENCIA1.AsFloat + CDSAlunoLancALUDISFREQUENCIA2.AsFloat + CDSAlunoLancALUDISFREQUENCIA3.AsFloat) / 3, 2);

        CDSAlunoLancALUDISNOTA.AsFloat :=
             Arredonda( (CDSAlunoLancALUDISNOTA1.AsFloat + CDSAlunoLancALUDISNOTA2.AsFloat + CDSAlunoLancALUDISNOTA3.AsFloat) / 3, 2);
            //CDSAlunoDisciplinaALUDISNOTA4.AsFloat;
    end;
end;

procedure TDm.CDSAlunoDisciplinaAfterEdit(DataSet: TDataSet);
begin
    if dm.CDSAlunoDisciplinaALUDISDATA.asDateTime < StrToDate('01/01/2000') then
        dm.CDSAlunoDisciplinaALUDISDATA.asDateTime := date;
end;

procedure TDm.CDSAlunoLancAfterEdit(DataSet: TDataSet);
begin
    if dm.CDSAlunoLancALUDISDATA.asDateTime < StrToDate('01/01/2000') then
        dm.CDSAlunoLancALUDISDATA.asDateTime := date;
end;

procedure TDm.CDSLctoContabilReconcileError(DataSet: TCustomClientDataSet;
  E: EReconcileError; UpdateKind: TUpdateKind;
  var Action: TReconcileAction);
begin
    showmessage('Erro: ' + E.Message);
end;

end.

